.TH bflen 1 "4 May 2006"
.SH NAME
bflen \- compute length of a BF program
.SH SYNOPSIS
\fBbflen\fR \fB<\fR\fIBF-program-file-name\fR
.SH DESCRIPTION
\fBbflen\fR computes the length of a BF program, in characters.  The program
is read from the standard input.  Comment characters are not counted towards
the length.
.SH "SEE ALSO"
bfdb(1), bfref(1)
.SH AUTHOR
David Moews \- dmoews@fastmail.fm
