// This module factors out lists of simple strings that
// could potentially be used by different procedural generators

let labels = [
    "0agent/dispatcher",
    "1handler/budget",
    "1handler/focus",
    "1handler/new_projects",
    "1handler/relaxing",
    "1handler/weekly",
    "5device/morning",
    "5device/weekly",
    "6project/datadog-strategy",
    "6project/divorce",
    "6project/exomustard",
    "6project/how-to-collaborate-with-machines",
    "6project/levers-of-capitalism",
    "6project/mapcamp-talk",
    "6project/org-resolution-at-edge",
    "6project/volcano-beginner",
    "6project/what-is-a-profunctor",
    "6project/yap-like"
    /*
    "7area",
    "7area/apartment",
    "7area/blog",
    "7area/body",
    "7area/datadog",
    "7area/finances",
    "7area/katie",
    "7area/keep",
    "7area/love",
    "7area/math",
    "7area/politics",
    "7area/research",
    "7area/self",
    "7area/weekly",
    "8resource/ai",
    "8resource/apartment",
    "8resource/audio",
    "8resource/aversion-factoring",
    "8resource/blog",
    "8resource/body",
    "8resource/bondgraph",
    "8resource/c",
    "8resource/cellularautomata",
    "8resource/ceu",
    "8resource/chaos-engineering",
    "8resource/cpp",
    "8resource/datascience",
    "8resource/debugging",
    "8resource/design",
    "8resource/discrete_event_simulation",
    "8resource/electronics",
    "8resource/ethics",
    "8resource/expert-systems",
    "8resource/factorio",
    "8resource/feature-toggles",
    "8resource/finances",
    "8resource/financial-bond-graphs",
    "8resource/fish",
    "8resource/funny",
    "8resource/gamedev",
    "8resource/go",
    "8resource/job",
    "8resource/kata",
    "8resource/keep",
    "8resource/love",
    "8resource/machinations",
    "8resource/magic",
    "8resource/math",
    "8resource/messydata",
    "8resource/officepolitics",
    "8resource/philosophy",
    "8resource/politics",
    "8resource/programming",
    "8resource/research",
    "8resource/risk",
    "8resource/rule-based",
    "8resource/self",
    "8resource/sre",
    "8resource/testing",
    "8resource/ui",
    "8resource/unix",
    "8resource/webfrontend",
    "8resource/wordle",
    "9archive/2006",
    "9archive/2011",
    "9archive/2013",
    "9archive/2018",
    "9archive/2019",
    "9archive/2020",
    "9archive/2021",
    "9archive/2022",
    "9archive/art-of-memory",
    "9archive/audio",
    "9archive/blog",
    "9archive/datadog",
    "9archive/gamedev",
    "9archive/glitch",
    "9archive/google",
    "9archive/hank",
    "9archive/idexx",
    "9archive/lesswrong",
    */
  ];
  
  let letters = "abcdefghijklmnopqrstuvwxyz".split("");
  
  let action_process = [
    "GATHER",
    "CURSE",
    "ANNOUNCE",
    "TASTE (SOMETHING)",
    "INTEND",
    "PRAY",
    "MOISTEN",
    "GELD",
    "DISPEL",
    "LIBERATE",
    "SPREAD OUT",
    "IGNORE",
    "LEAD (GUIDE)",
    "INJURE",
    "HOLLOW OUT",
    "BE SILENT",
    "REFUSE",
    "SHIVER",
    "SHRINK",
    "WHISPER",
    "INDUCE",
    "KNEEL",
    "DISGRACE",
    "WASTE",
    "FORBID",
    "GIVE BACK",
    "SIEVE",
    "SPOIL (SOMEBODY OR SOMETHING)",
    "DRAW MILK",
    "CRAWL",
    "BOAST",
    "FORNICATE",
    "HAILING",
    "DRUMMING",
    "IMITATE",
    "BEWITCH",
    "DIVE",
    "SPIN",
    "SWEAT (PERSPIRE)",
    "EXTINGUISH",
    "MUMBLE",
    "CHOKE",
    "WEAVE",
    "BATHE",
    "BURN (SOMETHING)",
    "RETURN HOME",
    "WORRY",
    "CHOP",
    "DYE",
    "PUT ON",
    "SET (HEAVENLY BODIES)",
    "MISS (A TARGET)",
    "HICCOUGH",
    "REST",
    "BLOW (OF WIND)",
    "BLOW (WITH MOUTH)",
    "RIPEN",
    "CALL BY NAME",
    "BAKE",
    "MOW",
    "DONATE",
    "MARRY",
    "CAST",
    "STRETCH",
    "LIE DOWN",
    "TELL FORTUNES",
    "CARVE",
    "MOVE AWAY",
    "SWEEP",
    "SHAVE",
    "COST",
    "THRUST",
    "TAN",
    "HAPPEN",
    "SHARPEN (SOMETHING)",
    "FRIGHTEN",
    "CARE FOR",
    "STICKING",
    "WORSHIP",
    "DRIBBLE",
    "KNEAD",
    "PEEL",
    "THRESH",
    "FORGE",
    "MOLD",
    "PULL OFF (SKIN)",
    "CROUCH",
    "SHRIEK",
    "SCOLD",
    "ABSTAIN FROM FOOD",
    "PREACH",
    "LICK",
    "CHEW",
    "UNTIE",
    "STRIKE",
    "POUND",
    "CUT DOWN",
    "HANG UP",
    "FAN (ACTION)",
    "DWELL (LIVE, RESIDE)",
    "SMEAR",
    "SPLASH",
    "LIMP",
    "RIDE",
    "OWE",
    "BARTER",
    "PICK UP",
    "SNIFF",
    "PINCH",
    "GOVERN",
    "RESPECT (SOMEBODY)",
    "BLESS",
    "PIERCE",
    "OPPRESS",
    "SURPASS",
    "CARRY IN HAND",
    "CARRY ON SHOULDER",
    "CARRY ON HEAD",
    "CARRY UNDER ARM",
    "RETREAT",
    "GET LOST",
    "TWIST",
    "SNAP (OF STICK)",
    "BREAK (OF ROPE)",
    "FELL (A TREE)",
    "CARRY ON BACK",
    "SPEAR (SOMEBODY)",
    "GROW",
    "CONDEMN",
    "DISAPPEAR",
    "FLIRT",
    "REVENGE",
    "CURE",
    "LIFT",
    "LEARN",
    "SEE A DOCTOR",
    "HOWL",
    "COPULATE",
    "DILUTE",
    "DISLOCATE",
    "GROW UP",
    "HEW",
    "HINDER",
    "INFRINGE",
    "MARRY OFF",
    "OFFEND",
    "PASS BY",
    "REBEL",
    "RISE (MOVE UPWARDS)",
    "SPOIL (BECOME SPOILED)",
    "STAND UP",
    "STING",
    "STREW",
    "SWAY",
    "TRANSIT",
    "TREAD",
    "KISS",
    "COME BACK",
    "LEND",
    "PISS",
    "LIE (MISLEAD)",
    "HIDE (CONCEAL)",
    "SHIT (DEFECATE)",
    "BREAK (DESTROY OR GET DESTROYED)",
    "DESTROY",
    "OWN",
    "DECIDE",
    "BRING",
    "GET",
    "GO",
    "STIR",
    "CONTAIN",
    "CARRY",
    "CATCH",
    "GO UP (ASCEND)",
    "REMEMBER",
    "SHINE",
    "TEACH",
    "STEAL",
    "SHOUT",
    "GROAN",
    "PAY",
    "FIND",
    "READ",
    "EARN",
    "MAKE",
    "LIGHT (IGNITE)",
    "FEED",
    "DRIVE",
    "SOW SEEDS",
    "ENTER",
    "DROP",
    "HURRY",
    "DENY",
    "DEPEND",
    "COVER",
    "SUIT",
    "MOVE",
    "HAVE",
    "SAIL",
    "BOIL (OF LIQUID)",
    "DRIP (FALL IN GLOBULES)",
    "DO",
    "DRESS UP",
    "ROLL",
    "ENDURE",
    "ERR",
    "SEIZE",
    "HIRE",
    "WIN",
    "COUGH",
    "REPEAT",
    "SHARE",
    "SWALLOW",
    "TRADE",
    "LOVE",
    "EMBRACE",
    "STRAIN",
    "FLEE",
    "BRAKE",
    "MUST",
    "BE ABLE",
    "WEAR",
    "CONVICT",
    "REMAIN",
    "ACQUIT",
    "FRY",
    "PUT",
    "PERMIT",
    "SOIL",
    "WHISTLE",
    "YAWN",
    "GRIND",
    "SHOW",
    "INCREASE",
    "SHUT",
    "PURSUE",
    "EMERGE (APPEAR)",
    "FEEL",
    "CALL",
    "FOLLOW",
    "WORK (ACTIVITY)",
    "CONCEIVE",
    "SINK (DESCEND)",
    "BE BORN",
    "HOPE",
    "FASTEN",
    "LET GO OR SET FREE",
    "ABANDON",
    "WEIGH",
    "RESIDE",
    "COOK (SOMETHING)",
    "SUFFER",
    "CLIMB",
    "FALL ASLEEP",
    "GO OUT",
    "UNCOVER",
    "SUCCEED",
    "WRAP",
    "DAMAGE",
    "LIKE",
    "ACCUSTOM",
    "DIVIDE",
    "SEND",
    "ORDER",
    "KICK",
    "BEGET",
    "OPEN",
    "FART",
    "BRIBE (SOMEBODY)",
    "TRAP (CATCH)",
    "SHOOT",
    "DIMINISH",
    "LAST (ENDURE)",
    "THREATEN",
    "GIVE BIRTH",
    "BARKING",
    "RAIN (RAINING)",
    "SNOWING",
    "SING",
    "CHANGE",
    "DELIGHT",
    "ANSWER",
    "VOMIT",
    "FALL",
    "ASK (INQUIRE)",
    "RAISE",
    "SLIP",
    "DEFEND",
    "EAT",
    "HEAT UP",
    "LAUGH",
    "SEPARATE",
    "VISIT",
    "ARRIVE",
    "DRINK",
    "BITE",
    "BREATHE",
    "HEAR",
    "SEE",
    "KNOW (SOMETHING)",
    "LIE (REST)",
    "PLAY",
    "SQUEEZE",
    "THINK (REFLECT)",
    "SIT",
    "KILL",
    "DIG",
    "FEAR (BE AFRAID)",
    "COUNT",
    "SUCK",
    "BE ALIVE",
    "FIGHT",
    "BURNING",
    "FREEZE",
    "CUT",
    "HIT",
    "STAB",
    "HUNT",
    "SCRATCH",
    "SPLIT",
    "SWIM",
    "SPIT",
    "FLY (MOVE THROUGH AIR)",
    "STAND",
    "WALK",
    "TURN AROUND",
    "TURN (SOMETHING)",
    "COME",
    "GIVE",
    "HOLD",
    "RUB",
    "SMILE",
    "PUSH",
    "WASH",
    "WIPE",
    "PULL",
    "THROW",
    "SEW",
    "SAY",
    "LOOK FOR",
    "FOLD",
    "KEEP",
    "PLANT (SOMETHING)",
    "POUR",
    "DIE",
    "BORE",
    "MEASURE",
    "RISE (ONESELF)",
    "THINK (BELIEVE)",
    "SUBJUGATE",
    "RUN",
    "CRUSH",
    "SEEM",
    "FORGET",
    "FORGIVE",
    "SHEAR",
    "BE HUNGRY",
    "UNDERSTAND",
    "CULTIVATE",
    "ACCOMPANY",
    "PREVENT",
    "ARRANGE",
    "SELL",
    "SWELL",
    "FLOAT",
    "PILE UP",
    "BE",
    "SLEEP",
    "SMELL (PERCEIVE)",
    "SMELL (STINK)",
    "TURN",
    "WAIT (FOR)",
    "WAKE UP",
    "HATE",
    "LISTEN",
    "INVITE",
    "ESCAPE",
    "SNEEZE",
    "SPEAK",
    "EXPLAIN",
    "OBEY",
    "SIT DOWN",
    "WATCH",
    "BLINK",
    "LOSE",
    "BEAT",
    "WRITE",
    "PROMISE",
    "SMOKE (INHALE)",
    "SURRENDER",
    "TELL",
    "BURY",
    "RESULT IN",
    "PLAIT OR BRAID OR WEAVE",
    "TEAR (SHRED)",
    "DECORATE",
    "TRAVERSE",
    "JOIN",
    "TAKE",
    "CHOOSE",
    "LEAVE",
    "UNDRESS",
    "FINISH",
    "SCRAPE",
    "RESEMBLE",
    "APPROACH",
    "DARE",
    "WANT",
    "HAVE SEX",
    "DRY UP",
    "SLAUGHTER",
    "BEGIN",
    "TRY",
    "ACCUSE",
    "ACHE",
    "ADJUDICATE",
    "LOOK",
    "BORROW",
    "HARVEST CROPS",
    "ASK (REQUEST)",
    "JUMP",
    "MEET",
    "CRY",
    "BUILD",
    "SUSPECT",
    "RULE",
    "ROW",
    "STUTTER",
    "BUY",
    "REGRET",
    "DANCE",
    "BELIEVE",
    "TOUCH",
    "HELP",
    "BETRAY",
    "DROWN",
    "SHAKE",
    "DRAW (WATER)",
    "PRESS",
    "TIE",
    "DREAM (SOMETHING)",
    "PLOUGH",
    "LAND (DESCEND)",
    "CEASE",
    "STUDY",
    "GUESS",
    "LOOSEN",
    "SWEAR",
    "PASS",
    "TORTURE",
    "GRIEVE",
    "ROAST (SOMETHING)",
    "CHECK",
    "RECOVER",
    "SNORE",
    "BECOME",
    "GET TIRED",
    "PRESERVE",
    "COMMAND",
    "OVERCOME",
    "PAINTING",
    "FLOW",
    "BEND",
    "FILL",
    "RESCUE",
    "INVESTIGATE",
    "GO DOWN (DESCEND)",
    "MAKE DRY",
    "MIX",
    "GRASP",
    "ADMIT",
    "TUG",
    "DRAG",
    "PUT OUT TO PASTURE",
    "WARM UP",
    "DELIVER",
    "QUILT",
    "CLOSE (EYES)",
    "SCATTER (SEEDS)",
    "STEP (VERB)",
    "PULL UP (RICE SEEDLINGS)",
    "STEAM (VERB)",
    "BRAISE (VERB)",
    "SOAK (VERB)",
    "COMB (VERB)",
    "LAY (VERB)",
    "USE (VERB)",
    "ROB (VERB)",
    "CROW (VERB)",
    "BROOD (VERB)",
    "SPROUT (VERB)",
    "BE DEAD OR DIE",
    "BURN",
    "HOLD OR TAKE",
    "FEAR OR FRIGHTEN",
    "CEASE OR FINISH",
    "REST OR SLEEP",
    "DESIRE",
    "SMELL",
    "STRIKE OR BEAT",
    "RAISE (BRING UP)",
    "TRADE OR BARTER",
    "RUN AWAY",
    "ROAST OR FRY",
    "PICK",
    "CHOP (INTO PIECES)",
    "THERE IS OR THERE ARE",
    "CARRY PERSON ON BACK",
    "CUT (WITH SCISSORS)",
    "CUT (WITH KNIFE)",
    "STIR FRY",
    "MARRY (AS WOMAN)",
    "MARRY (AS MAN)",
    "CATCH A COLD",
    "REJOICE",
    "CARP",
    "BE AT WAR",
    "BECOME EXTINGUISHED",
    "BECOME PREPARED (OF FOOD)",
    "CLOSE THE EYES",
    "ARRIVE (OF AN EVENT)",
    "BECOME ANGRY",
    "BECOME NUMB",
    "YOKE (VERB)",
    "MOVE QUICKLY",
    "NOMADIZE",
    "CONJURE",
    "BE ANGRY",
    "BEND (SOMETHING)",
    "RECEIVE VISITORS",
    "SPAWN (VERB)",
    "BECOME SOUR",
    "CORRECT (SOMETHING OR SOMEBODY)",
    "FALL (OF SNOW AND RAIN)",
    "CLEAN (SOMETHING)",
    "FIND OUT",
    "KNOW HOW",
    "REPAIR",
    "BELCH",
    "KNOW (SOMEBODY)",
    "DRIP (EMIT LIQUID)",
    "SET ALIGHT (SOMETHING)",
    "THINK",
    "LIVE",
    "GET WET",
    "PULL OUT",
    "TAKE OFF ONE'S CLOTHES",
    "BECOME SICK",
    "MISS (SOMEBODY)",
    "LACK (NOT HAVE)",
    "MELT",
    "FLASH (VERB)",
    "THUNDER (VERB)",
    "CONGEAL (BLOOD)",
    "KNOCK",
    "HURT (SOMEBODY)",
    "THANK (SOMEBODY)",
    "WINNOWING",
    "LAY EGGS",
    "SUCKLE (BREASTFEED, NURSE)",
    "HIDE (ONESELF)",
    "HIDE",
    "BOIL (SOMETHING)",
    "BOIL",
    "LAUNDER (WASH CLOTHES)",
    "EXCHANGE",
    "BREAK (CLEAVE)",
    "FEEL (TACTUALLY)",
    "HURT (SENSE PAIN)",
    "CASTRATE",
    "TRY (TEST)",
    "SENSE (PERCEIVE BY SENSES)",
    "DO OR MAKE",
    "FISHING",
    "FISHING (WITH A NET)",
    "BE IGNORANT",
    "DO NOT DO IT",
    "BLOW (WITH NOSE)",
    "FADE (LOOSE COLOR)",
    "INHALE",
    "GNAW",
    "CLOG (SOMETHING)",
    "TALK",
    "FLATTER",
    "TAKE A PHOTO",
    "TRANSPORT",
    "GET DIZZY",
    "HAVE A FEVER",
    "HAVE DIARRHEA",
    "DESPISE",
    "BLAME (SOMEBODY)",
    "RECOMMEND",
    "MAKE A JOKE",
    "BEND (ONESELF)",
    "BLOCK (THE WAY)",
    "CARRY HORIZONTALLY",
    "CONSUME (DRINK OR EAT)",
    "LADLE (WATER)",
    "BURP",
    "FISHING (WITH A HOOK)",
    "BLACKEN",
    "MENSTRUATE",
    "CHANGE (SOMETHING)",
    "CHANGE (BECOME DIFFERENT)",
    "STREAM (FLOW CONTINUOUSLY)",
    "SMOKE (EMIT SMOKE)",
    "BOLT (MOVE IN HASTE)",
    "BUDGE (ONESELF)",
    "CONNECT",
    "DASH (OF VEHICLE)",
    "DECREASE",
    "DIE (FROM ACCIDENT)",
    "DROP (SOMETHING)",
    "CALCULATE",
    "DRIVE (CATTLE)",
    "BOTHER (HARASS)",
    "RECOGNIZE (SOMEBODY)",
    "SWING (MOVEMENT)",
    "IMPROVE (SOMETHING)",
    "MOVE (AFFECT EMOTIONALLY)",
    "MOVE (ONESELF)",
    "RING (MAKE SOUND)",
    "ROAR (OF SEA)",
    "RUSTLE (OF LEAVES)",
    "SEAT (SOMEBODY)",
    "SOUND (OF INSTRUMENT OR VOICE)",
    "HALT (STOP)",
    "URGE (SOMEONE)",
    "ADD",
    "DISTURB",
    "HANG",
    "HERD (SOMETHING)",
    "PRODUCE",
    "THAW (DEW)",
    "TINKLE",
    "TWINKLE",
    "WALK (TAKE A WALK)",
    "TIE UP (TETHER)",
    "MAKE ANGRY (ANNOY)",
    "NOTICE (SOMETHING)",
    "TUMBLE (FALL DOWN)",
    "MAKE NOISE",
    "CAUSE TO (LET)",
    "CHIME (ACTION)",
    "CONVEY (A MESSAGE)",
    "JOG (SOMETHING)",
    "PROTECT",
    "SWING (SOMETHING)",
    "BRAWL (FIGHT)",
    "CHAT (WITH SOMEBODY)",
    "RINSE",
    "KNIT",
    "TRANSLATE",
    "ROT",
    "PREPARE",
    "BREAK (BREAKING)",
    "BEAR FRUIT",
    "SWINDLE",
    "GRAZE",
    "COOL DOWN",
    "HOLD A MEETING",
    "INSERT",
    "MISPLACE",
    "MANAGE",
    "FIX",
    "IRRIGATE",
    "SPLIT OPEN",
    "MINCE (SOMETHING)",
    "BOX (SOMEBODY OR SOMETHING)",
    "BRUSH (TEETH)",
    "CLAP",
    "CONDUCT",
    "ERUPT",
    "FILE (SOMETHING)",
    "GRATE (SOMETHING)",
    "HAMMER (SOMETHING)",
    "HATCH (OUT)",
    "HITCHHIKE",
    "IRON (CLOTHES)",
    "MASSAGE (SOMEBODY)",
    "MOP (SOMETHING)",
    "OPERATE (MEDICINE)",
    "PAINT (SOMETHING)",
    "PHOTOGRAPH (SOMETHING)",
    "PLAY (INSTRUMENT)",
    "PLAY (GAME)",
    "POST (SOMETHING)",
    "RAKE (SOMETHING)",
    "SHOWER (ACTION)",
    "SKATE",
    "SPILL (SOMETHING)",
    "SUNBATHE",
    "SURF",
    "TALK (PHONE)",
    "TYPE (ON SOMETHING)",
    "VACUUM (SOMETHING)",
    "WATCH (TV)",
    "CUT (WITH AXE)",
    "SLAP",
    "CHEW BETEL",
    "SQUAT",
    "BATHE (SOMEONE)",
    "WAKE UP (SOMEONE)",
    "SHOOT (WITH SLINGSHOT)",
    "STAB TO DEATH",
    "PAINT (SOMETHING) OR PAINTING",
    "DAMAGE OR INJURE",
    "TWIST (AROUND)",
    "HINDER OR PREVENT",
    "INSULT",
    "GO UP OR RISE (ONESELF)",
    "MAKE A SPEECH",
    "HOPE (SOMETHING)",
    "HIRE OR RENT",
    "CREEP",
    "WRING",
    "DECEIVE",
    "OPEN (EYES)",
    "TWIST (TOGETHER)",
    "ALLOW OR PERMIT",
    "ALLOW",
    "AMUSE ONESELF (HAVE FUN)",
    "TILL",
    "ENCIRCLE",
    "BLOOM",
    "IMPEL",
    "DRIVE OR IMPEL OR RIDE",
    "BRAID (VERB) OR WEAVE (BASKET)",
    "BRAID (VERB)",
    "WEAVE (BASKET)",
    "BRAWL",
    "QUARREL (VERB)",
    "NAIL",
    "HIT (A TARGET)",
    "STRIKE (SOMEONE)",
    "STRIKE (SOMETHING)",
    "FASTING",
    "BELIEF (RELIGIOUS)",
    "FUNERAL",
    "LIBATE",
    "GET UP FROM BED",
    "STOP DOING",
    "DRIP OR DROP SOMETHING",
    "NOT HAVE",
    "DRY IN SUN",
    "RELY ON",
    "WASH (ONESELF)",
    "SCALD (BURN ONESELF WITH LIQUID)",
    "WEAR (ON HEAD)",
    "COMPARE",
    "CELEBRATE NEW YEAR",
    "WASH (CLOTHES)",
    "OPEN (MOUTH)",
    "CARRY (WITH POLE ON SHOULDER)",
    "BEGIN OR START",
    "SIEVE OR STRAIN",
    "START",
    "COMMEND",
    "CRAWL OR CREEP",
    "PUT IN ORDER",
    "GROW PLANTS",
    "LONG (FOR SOMETHING)",
    "BE THIRSTY",
    "BEG",
    "BE DEFEATED",
    "DOUBT (SOMETHING)",
    "TURN OVER",
    "TAKE OFF",
    "BURN LAND",
    "SAW (SOMETHING)",
    "WAVE (VERB)",
    "CLOSE (MOUTH)",
    "PULL UP WEEDS",
    "PATCH",
    "FETCH",
    "GREET",
    "PANT",
    "BLEED",
    "FAINT (PASS OUT)",
    "STUMBLE",
    "STAMP",
    "LEAN",
    "KNOW",
    "SURPRISE (SOMEBODY)",
    "HONOR (SOMEBODY)",
    "HESITATE",
    "PRETEND",
    "ASSEMBLE (GET TOGETHER)",
    "AVOID",
    "GOSSIP",
    "SLANDER",
    "COMPLAIN",
    "AGREE",
    "PERSUADE",
    "TICKLE (SOMEBODY)",
    "SERVE (SOMEONE)",
    "PUNISH",
    "APPLY (OINTMENT)",
    "FERMENT",
    "TAKE OUT",
    "STORE UP",
    "PACK",
    "POLISH (SOMETHING)",
    "SHELL (SOMETHING)",
    "INHERIT",
    "TRAVEL",
    "WANDER",
    "PADDLE (MOVEMENT)",
    "LOAD (SOMETHING)",
    "PLUNDER",
    "HUM",
    "DIVORCE (SEPARATE)",
    "GROWL",
    "RUMINATE",
    "PERCH (OF BIRD)",
    "CACKLE",
    "PECK",
    "HISS",
    "SQUEAK",
    "THROW AWAY",
    "DIP",
    "SINGE",
    "CONTINUE",
    "LENGTHEN",
    "SCATTER",
    "POUND (FOOD)",
    "SCREAM (PRODUCE A CRY)",
    "RENT (SOMETHING)",
    "PUT (IN A SITTING POSITION)",
    "PUT (IN A STANDING POSITION)",
    "ITCH (CAUSE ITCHING OR FEEL ITCHY)",
    "FAIL",
    "HEAR OR LISTEN",
    "IMAGINE",
    "CUT OR HACK",
    "ACQUIRE (SOMETHING)",
    "AFFORD",
    "ATTACH",
    "DETECT",
    "ROAR",
    "ACCEPT",
    "ATTACKING",
    "TAMING",
    "TRUST (SOMEBODY)",
    "SYMPATHIZE",
    "ENCOUNTER (MEET)"
  ];
  
  let person_thing = [
    "DUST",
    "COURTYARD",
    "GAZELLE",
    "EARTHQUAKE",
    "FIREWOOD",
    "DARKNESS",
    "MIDDAY",
    "DECEIT",
    "YOKE",
    "OTTER",
    "SLED",
    "EYELID",
    "EARLOBE",
    "FISHING LINE",
    "SCYTHE",
    "RYE",
    "DIRT",
    "AIR",
    "PAN",
    "EARWAX",
    "NETTLE",
    "STAIRS",
    "TAMARIND",
    "PUBIC HAIR",
    "ENVY",
    "EXCRETA",
    "JACK",
    "SORE",
    "SPIRIT",
    "BAD LUCK",
    "ELECTRICITY",
    "OAT",
    "RUMOUR",
    "PIN",
    "AMBUSH",
    "EMBERS",
    "TATTOO",
    "CLAW",
    "BEAK",
    "PUPPY",
    "YOUNG MAN",
    "YOUNG WOMAN",
    "DOORPOST",
    "FATHOM",
    "ANGER",
    "BEEHIVE",
    "NATIVE COUNTRY",
    "SANDFLY",
    "HUNCHBACK",
    "COMMON COLD (DISEASE)",
    "MATTRESS",
    "OMEN",
    "RUDDER",
    "MOTOR",
    "TURTLE",
    "SHORE",
    "PORPOISE",
    "PROFLIGATE",
    "LARCH",
    "PITCHER",
    "CART",
    "FOREHEAD",
    "THORN",
    "SWEAT (SUBSTANCE)",
    "FESTIVAL",
    "SAUCE",
    "FAULT",
    "BOOMERANG",
    "COCA",
    "GUMS",
    "PADDY FIELD",
    "MACHINE",
    "SUGAR CANE",
    "COCONUT TREE",
    "ITCH",
    "RAZOR",
    "HOOF",
    "UDDER",
    "SWEET POTATO",
    "KANGAROO",
    "WALLABY",
    "MAINLAND",
    "MAIL",
    "FATHER'S SISTER",
    "MOTHER'S SISTER",
    "SHOULDERBLADE",
    "SIBLING'S CHILD",
    "BETEL PEPPER VINE",
    "ANTEATER",
    "SPOKE",
    "MAST",
    "FIREPLACE",
    "SHIN",
    "LOIN",
    "COMB OF BIRD",
    "HAIR (BODY)",
    "NUT",
    "CORNER",
    "FAMILY",
    "MAT",
    "GENITALIA",
    "FAMINE",
    "FARM",
    "STRENGTH",
    "TROUGH",
    "FIREFLY",
    "NASAL MUCUS (SNOT)",
    "LIFE",
    "FIELD",
    "FIN",
    "MOVIE",
    "BETELNUT",
    "FINE (PENALTY)",
    "TOILET",
    "FIRE",
    "THRESHING-FLOOR",
    "MORTAR",
    "PESTLE",
    "FISH",
    "FLEA",
    "SNOWSHOE",
    "PADDLE",
    "FLYING FOX",
    "STEPMOTHER",
    "STEPFATHER",
    "PRAWNS",
    "FLOWER",
    "ELECTION",
    "TREE STUMP",
    "BROOM",
    "FOG",
    "SERVANT",
    "FOOD",
    "SAVANNA",
    "ARCTIC LIGHTS",
    "HERDSMAN",
    "HE-GOAT",
    "FOWL",
    "SCALE",
    "NIT",
    "JUG",
    "SAUCER",
    "TONGS",
    "DOUGH",
    "BANISTERIUM",
    "SPINDLE",
    "AWL",
    "THATCH",
    "RIDGEPOLE",
    "POST",
    "POLE",
    "PADDY",
    "HOE",
    "NEEDLE TREE",
    "CONE",
    "ADZE",
    "RUG",
    "NETBAG",
    "TUMPLINE",
    "WHETSTONE",
    "RATTLE",
    "CHIEFTAIN",
    "CLAN",
    "GRANDPARENTS",
    "PARENTS-IN-LAW",
    "HAWK",
    "TOUCAN",
    "OPOSSUM",
    "HEAD LOUSE",
    "BODY LOUSE",
    "TAPIR",
    "AGOUTI",
    "CAPYBARA",
    "CURASSOW",
    "PACA",
    "PIRANHA",
    "FOOTPRINT",
    "FIG",
    "FAT (ORGANIC SUBSTANCE)",
    "MANIOC FLOUR",
    "FELT",
    "CLOAK",
    "PONCHO",
    "GRASS-SKIRT",
    "STOCKING",
    "HEADBAND",
    "HEADDRESS",
    "RAG",
    "PLAIT",
    "COOKHOUSE",
    "MEETING HOUSE",
    "PADLOCK",
    "PITCHFORK",
    "RAKE",
    "DIGGING STICK",
    "LASSO",
    "SICKLE",
    "HAY",
    "VINE",
    "TREE TRUNK",
    "SAP",
    "BANYAN",
    "SORGHUM",
    "FISH POISON",
    "ACHIOTE",
    "MANGROVE",
    "TARO",
    "SHEARS",
    "TINPLATE",
    "POTTER",
    "PEG",
    "STRING",
    "SLEDGE",
    "BLAME",
    "MASTER",
    "FREEMAN",
    "BATTLE-AXE",
    "SLING",
    "FISHNET",
    "FISH TRAP",
    "PUNISHMENT",
    "MAGIC",
    "CIRCUMCISION",
    "SHAMAN (FOLK HEALER)",
    "PILL",
    "TABLET",
    "BIRTH CERTIFICATE",
    "PLANTAIN",
    "MUSH",
    "GARDEN-HOUSE",
    "ALCOHOL (FERMENTED DRINK)",
    "OLDER SIBLING",
    "OLD MAN",
    "MANIOC BREAD",
    "MEN'S HOUSE",
    "FORKED BRANCH",
    "YAM",
    "GOURD",
    "OUTRIGGER",
    "FOREST",
    "NECESSITY",
    "MARRIED MAN",
    "MARRIED WOMAN",
    "YOUNGER SIBLING",
    "SWIDDEN FIELD",
    "UPPER ARM",
    "BLOWGUN",
    "HOWLER MONKEY",
    "SPIDER MONKEY",
    "COLLARED PECCARY",
    "WHITE-LIPPED PECCARY",
    "GUAN",
    "CHIGGOE (JIGGER FLEA)",
    "CEBUS MONKEY",
    "CHONTA PALM",
    "CHICHA",
    "FRONT TOOTH (INCISOR)",
    "TIP (OF TONGUE)",
    "LONG HAIR",
    "UPPER BACK",
    "LOWER ARM",
    "LOWER LEG",
    "STORM CLOUDS",
    "CORN FIELD",
    "CUSHMA",
    "HARMATTAN",
    "DRY SEASON",
    "RAINY SEASON",
    "SHEA NUT TREE",
    "MAHOGANY TREE",
    "GUINEA FOWL",
    "BLIND PERSON",
    "DEAF PERSON",
    "BOUBOU",
    "WRAPPER",
    "ALANG-ALANG GRASS",
    "CASSOWARY",
    "CRAYFISH",
    "G-STRING",
    "PANDANUS",
    "POSSUM",
    "UPPER LEG (THIGH)",
    "PELICAN",
    "DRESS",
    "UNTRUTH",
    "CUP",
    "LIP",
    "PLATE",
    "DISH",
    "NOBLE",
    "COMPOUND",
    "MINISTER",
    "MANNER",
    "KIDNEY",
    "DESCENDANTS",
    "CENTER",
    "CUCUMBER",
    "SCAR",
    "CALF OF LEG",
    "NAIL (TOOL)",
    "FROG",
    "PARENTS",
    "MAIZE",
    "MELON",
    "PERIOD",
    "BAOZI",
    "FIREDRILL",
    "SPARK",
    "SPOT",
    "MANZANITA",
    "TULE",
    "WOLF",
    "BACK OF HEAD",
    "BARBEL",
    "BLOOD VESSEL",
    "DOG-ROSE",
    "FLANK",
    "FRECKLE",
    "GIPSY",
    "GLUTTON",
    "HUMP",
    "TURBID",
    "MULTITUDE",
    "NEST",
    "PALATE",
    "POETRY",
    "SHUTTLE",
    "SPRUCE",
    "SUCKER",
    "SURFACE",
    "BROTHER (OF MAN)",
    "BROTHER (OF WOMAN)",
    "SISTER (OF MAN)",
    "SISTER (OF WOMAN)",
    "DANDRUFF",
    "FOREFINGER",
    "BATTLE",
    "FUR",
    "BOOT",
    "GARDEN",
    "ANT",
    "ADDRESS",
    "POTATO",
    "PIECE",
    "GROUNDNUT (PEANUT)",
    "POSTAGE STAMP",
    "PHYSICIAN",
    "SHELL",
    "DRIVER'S LICENSE",
    "COAT",
    "GLASS",
    "GRAIN",
    "GRASS",
    "GRASSHOPPER",
    "GULF",
    "HAIL",
    "PORT",
    "HARVEST",
    "HEAT",
    "HIGH TIDE",
    "HILL",
    "HORSE",
    "HOSPITAL",
    "ICE",
    "PRECIPICE",
    "ANIMAL",
    "INSECT",
    "IRON",
    "ISLAND",
    "LAGOON",
    "LAKE",
    "LAMP",
    "LAND",
    "LEAD (CHEMICAL ELEMENT)",
    "LEAF",
    "LEATHER",
    "LIGHT (RADIATION)",
    "LIVESTOCK",
    "LIZARD",
    "MARKET",
    "MEAT",
    "MILK",
    "MILL",
    "MOSS",
    "MOTORCYCLE",
    "MOUNTAIN",
    "MUD",
    "MUSHROOM",
    "MUSIC",
    "NEED (NOUN)",
    "OAK",
    "OCEAN",
    "ASH",
    "PAINT (PIGMENTS)",
    "PAPER",
    "PASTURE",
    "PETROLEUM",
    "SEAL",
    "PLAIN",
    "PLANT (VEGETATION)",
    "PLASTIC",
    "POISON",
    "POLICE",
    "PRICE",
    "RAIN (PRECIPITATION)",
    "REED",
    "REEF",
    "RELIGION",
    "BATTERY",
    "BAY",
    "RESIN",
    "BEE",
    "RIVER",
    "ROAD",
    "ROCK",
    "RODENT",
    "ROOT",
    "SAND",
    "SCHOOL",
    "MOUTH",
    "FAECES (EXCREMENT)",
    "AXE",
    "BEARD",
    "SIDE",
    "PERSON",
    "LUNG",
    "BOTTOM",
    "SEASON",
    "WHEEL",
    "SEED",
    "GOOD LUCK",
    "ATTACK",
    "PLACE (POSITION)",
    "OLD PERSON",
    "WHILE",
    "DAWN",
    "SNAKE",
    "BEVERAGE",
    "OWL",
    "YARD",
    "THING",
    "SHIP",
    "END (OF SPACE)",
    "END (OF TIME)",
    "EGG",
    "SHELF",
    "SHOP",
    "BICYCLE",
    "SHRUB",
    "STORE",
    "PUPIL (STUDENT)",
    "BUTTON",
    "HERON",
    "SILVER",
    "KNOT",
    "SKIN",
    "MENSTRUATION",
    "CORPSE",
    "LUNCH",
    "ROOF",
    "EARRING",
    "HAT",
    "BELT",
    "CABBAGE",
    "TRUMPET",
    "TRUNK OF TREE",
    "FLUTE",
    "SMOKE (EXHAUST)",
    "PART",
    "FEAR (FRIGHT)",
    "DEFEAT",
    "VICTORY",
    "SNOW",
    "SAILCLOTH",
    "SOAP",
    "PEOPLE",
    "STRANGER",
    "BOIL (OF SKIN)",
    "PEN",
    "TROUT",
    "NIPPLE",
    "TESTICLES",
    "JAW",
    "WRIST",
    "THIGH",
    "RIB",
    "ADAM'S APPLE",
    "ANKLE",
    "WOMB",
    "SPINE",
    "BLANKET",
    "TROUSERS",
    "LOCUST",
    "SOUL",
    "SLAVE",
    "GOVERNMENT",
    "HALF",
    "WILLOW",
    "STOMACH",
    "LAMB",
    "POPLAR",
    "SORCERER",
    "WITCH",
    "BRANCH (BIFURCATION)",
    "RACCOON",
    "RAFTER",
    "SOOT",
    "BASE",
    "BEAN",
    "BUTTOCKS",
    "CHAPTER",
    "SCREWDRIVER",
    "REMAINS",
    "CORMORANT",
    "FISHING SPEAR",
    "LIQUOR",
    "SPIDER",
    "KIND (THING)",
    "MURDER",
    "TIGER",
    "THIRST",
    "SPRING (OF WATER)",
    "SQUARE",
    "STABLE",
    "PRIEST",
    "ALTAR",
    "KETTLE",
    "STONE",
    "STORM",
    "STOVE",
    "CAUSE",
    "JUDGE",
    "SUGAR",
    "EDGE",
    "PUMPKIN",
    "FAME",
    "GLOVE",
    "BANANA",
    "BLADE",
    "BREATH",
    "RATTLESNAKE",
    "TAR",
    "TAX",
    "CANDY",
    "SHOEMAKER",
    "ARCH",
    "MASON",
    "HELL",
    "TAILOR",
    "PARROT",
    "TERMITE",
    "PARAKEET",
    "FLAME",
    "MULE",
    "TIDE",
    "TIME",
    "TIN (METAL)",
    "TOAD",
    "TORTOISE",
    "ANACONDA (WATER BOA)",
    "PRESIDENT",
    "TRAIN",
    "ADOBE",
    "ADULTERY",
    "ASPEN",
    "BERRY",
    "TREE",
    "OLD WOMAN",
    "DRUM",
    "GARBAGE",
    "DEATH",
    "TEMPLE",
    "COYOTE",
    "CROW",
    "SCULPTOR",
    "SINK (BASIN)",
    "LINEN",
    "ORNAMENT",
    "INCLINATION",
    "CHILI PEPPER",
    "GRAPE",
    "VALLEY",
    "PEAR",
    "VEGETABLES",
    "CASSAVA",
    "RICE",
    "MANIOC",
    "VERMIN",
    "VILLAGE",
    "MILLET",
    "BARLEY",
    "WALL (OF HOUSE)",
    "BUFFALO",
    "WAR",
    "STALLION",
    "BIRD",
    "MARE",
    "HORN (INSTRUMENT)",
    "MEAD",
    "HONEY",
    "WATERFALL",
    "SALMON",
    "SPEAR",
    "BLOOD",
    "STREAM",
    "WATER",
    "WATER LEECH",
    "SEAGULL",
    "WEAPONS",
    "WEATHER",
    "RAPE",
    "WELL",
    "WHALE",
    "WILD ANIMAL",
    "WAGON",
    "WIND",
    "PEBBLES",
    "WOMAN",
    "BOOK",
    "WOOL",
    "WORLD",
    "YEAST",
    "ACORN",
    "CIGARETTE",
    "COCONUT",
    "NOODLE",
    "TOBACCO",
    "SPINACH",
    "ARROW",
    "WAVE",
    "FARMER",
    "HEEL",
    "ELBOW",
    "LIME (FRUIT)",
    "WORK (LABOUR)",
    "VINEGAR",
    "TOMATO",
    "CREEK (TIDAL)",
    "CLIFF",
    "RIVER BED",
    "BOW",
    "QUIVER (FOR ARROWS)",
    "BAOBAB TREE",
    "JOINT",
    "ANXIETY",
    "BLACKSMITH",
    "STATUE",
    "MUSCLE",
    "TWINS",
    "BRICK",
    "COW",
    "BULL",
    "CHESTNUT TREE",
    "BOUNDARY",
    "BRIDGE",
    "LATCH",
    "FRESHWATER EEL",
    "DRIZZLE",
    "APPEARANCE",
    "MEMORY",
    "HANDKERCHIEF",
    "TOWEL",
    "BOOTY",
    "STUMP OF TREE",
    "CHARACTER",
    "LOW TIDE",
    "BUG",
    "JEWEL",
    "CITIZEN",
    "DEFENDANT",
    "OWNER",
    "ELF",
    "TEACHER",
    "HAIR",
    "CARPENTER",
    "BRAID",
    "PILLOW",
    "POET",
    "LINE",
    "MOLAR TOOTH",
    "MOTHER-IN-LAW",
    "CAN",
    "HUNTER",
    "SMALLPOX",
    "FATHER-IN-LAW",
    "SON-IN-LAW",
    "DAUGHTER-IN-LAW",
    "STEPDAUGHTER",
    "STEPSON",
    "CHILD-IN-LAW",
    "ARMOUR",
    "LAW",
    "NEPHEW",
    "SHIELD",
    "SPIDER WEB",
    "CRIME",
    "JUDGMENT",
    "COURT",
    "GLUE",
    "BUS",
    "HOOK",
    "PRISONER",
    "CAPTIVE",
    "FISHHOOK",
    "TRAP (PITFALL)",
    "WHEAT",
    "BILL",
    "MERCHANT",
    "MESS",
    "FRAXINUS",
    "MIDDLE",
    "SONG",
    "SACRIFICE",
    "NURSE",
    "CAMP",
    "WOUND",
    "SHARK",
    "CAR",
    "BULLET",
    "SPEECH",
    "WAGES",
    "PIPE",
    "CITRUS FRUIT",
    "BEAM",
    "MATCH",
    "DIVORCE",
    "RABBIT",
    "TENDON",
    "FAIRY",
    "LEOPARD",
    "FATIGUE",
    "PITY",
    "URINE",
    "OVEN",
    "WITNESS",
    "SWAMP",
    "AUBERGINE",
    "BRUISE",
    "ORPHAN",
    "THUNDER",
    "VEIL",
    "CATTLE",
    "OLIVE",
    "CAVE",
    "STEP",
    "THIEF",
    "THREAD",
    "INTENTION",
    "BRIBE (AMOUNT)",
    "MOUSTACHE",
    "MOULD",
    "GRUEL",
    "HAWTHORN",
    "OX",
    "MIRROR",
    "EYEBROW",
    "GHOST",
    "SPADE",
    "DIARRHEA",
    "NOSTRIL",
    "PALM TREE",
    "NOISE",
    "PALM OF HAND",
    "VULTURE",
    "GOOSE",
    "CHARCOAL",
    "ULCER",
    "HARE",
    "COOKED RICE",
    "STEAM",
    "BEAVER",
    "PENALTY",
    "BABOON",
    "WIFE",
    "HUSBAND",
    "FEATHER",
    "BARK",
    "TONGUE",
    "CAT",
    "MOTHER",
    "FATHER",
    "ROPE",
    "WORM",
    "TAIL",
    "NOSE",
    "PENIS",
    "HEART",
    "LIVER",
    "DAY (NOT NIGHT)",
    "YEAR",
    "BOARD",
    "EARTH (SOIL)",
    "NIGHT",
    "BUTTER",
    "EAR",
    "EYE",
    "SPIKE",
    "JAGUAR",
    "BELLY",
    "HOUSE",
    "HANDLE",
    "HEAD",
    "WING",
    "FINGERNAIL",
    "WEDDING",
    "DAY (24 HOURS)",
    "BROTHER",
    "SISTER",
    "BRIDE",
    "AUNT",
    "CANDLE",
    "SALT",
    "AUTUMN",
    "HAND",
    "PRISON",
    "FAT (FROM ANIMALS)",
    "BANK",
    "CAP",
    "BABY",
    "ELEPHANT",
    "BACK",
    "MISTAKE",
    "STICK",
    "WALKING STICK",
    "LEG",
    "NEWSPAPER",
    "COFFEE",
    "COUNTRY",
    "FOOT",
    "FORK",
    "FINGER",
    "CHILD (YOUNG HUMAN)",
    "CHIMNEY",
    "QUEEN",
    "LANGUAGE",
    "DOUBT",
    "FOX",
    "MOON",
    "RADIO",
    "TENT",
    "CHICKEN",
    "COWARD",
    "APPLE",
    "BOTTLE",
    "BREAKFAST",
    "CLOCK",
    "FRIEND",
    "UNCLE",
    "SCISSORS",
    "SHEEP",
    "NEIGHBOUR",
    "NECK",
    "GUTS",
    "PIG",
    "PEACE",
    "MORNING",
    "SUMMER",
    "SUN",
    "RAM",
    "EWE",
    "THROAT",
    "NAPE (OF NECK)",
    "BOAR (MALE PIG)",
    "CHURCH",
    "MONKEY",
    "SOW (FEMALE PIG)",
    "KNIFE",
    "HOUR",
    "NUMBER",
    "DAUGHTER",
    "ENEMY",
    "DUCK",
    "TOOL",
    "STREET",
    "VOICE",
    "KITCHEN",
    "BOY",
    "CROSS",
    "BREAD",
    "GOLD",
    "MONTH",
    "KNEE",
    "MEDICINE",
    "TEA",
    "RING",
    "WINDOW",
    "SPOON",
    "TELEPHONE",
    "TOOTH",
    "SHOE",
    "NEEDLE (FOR SEWING)",
    "GRANDFATHER",
    "PEPPER",
    "LION",
    "SHADE",
    "TOE",
    "TOWN",
    "LOUSE",
    "HORN (ANATOMY)",
    "BONE",
    "CLAY",
    "BREAST",
    "NAME",
    "STAR",
    "FOOL",
    "ROOM",
    "POT",
    "LADDER",
    "BOX",
    "CIRCLE",
    "WEEK",
    "WINTER",
    "KEY",
    "FIST",
    "SEA",
    "COMB",
    "CHAIR",
    "DOLPHIN",
    "BODY",
    "HAMMER",
    "SHOULDER",
    "OIL (ORGANIC SUBSTANCE)",
    "FAUCET",
    "CLOUD",
    "RAT",
    "MOUSE",
    "GRANDMOTHER",
    "POSTCARD",
    "JUICE",
    "GOAT",
    "SALIVA",
    "FLY (INSECT)",
    "SPERM",
    "FRUIT",
    "KING",
    "MOSQUITO",
    "CHIN",
    "ROOSTER",
    "HEN",
    "WASP",
    "SOCK",
    "WINE",
    "COAST",
    "MEAL",
    "TICK",
    "BOWL",
    "BRANCH",
    "FEVER",
    "SWORD",
    "SPRINGTIME",
    "SCORPION",
    "BASKET",
    "EYELASH",
    "SNAIL",
    "HOST",
    "SOUP",
    "TRIBE",
    "MAN",
    "CHAMELEON",
    "YOLK",
    "BEGINNING",
    "MONEY",
    "FACE",
    "ARMY",
    "MIND",
    "PYTHON",
    "HEAVEN",
    "GUN",
    "DOOR",
    "CHEESE",
    "COCKROACH",
    "IGUANA",
    "ALLIGATOR",
    "TIN (CAN)",
    "BRAIN",
    "BLISTER",
    "HUMMINGBIRD",
    "CHEST",
    "FLOUR",
    "SOUTH",
    "LOCK",
    "AIRPLANE",
    "NORTH",
    "WORD",
    "SKIRT",
    "MOSQUE",
    "TEMPLES",
    "SKULL",
    "IDEA",
    "PROSTITUTE",
    "LETTER",
    "COLOR",
    "SUMMIT",
    "CLOTH",
    "GRANDCHILD",
    "GRANDSON",
    "GRANDDAUGHTER",
    "SON",
    "SHIRT",
    "CHAIN",
    "SQUIRREL",
    "EVENING",
    "MACAW",
    "FLOOR",
    "AUTHORITY",
    "TRUTH",
    "BEER",
    "SIBLING",
    "SILK",
    "NIECE",
    "COUSIN",
    "RELATIVES",
    "GIRL",
    "FOAL",
    "ANVIL",
    "TEAR (OF EYE)",
    "LIGHTNING",
    "PUPIL",
    "DOLL",
    "STRAIT",
    "CAPE",
    "BED",
    "RAFT",
    "HOLE",
    "GRIEF",
    "ANCESTORS",
    "RAPIDS",
    "TOWER",
    "ARM",
    "WORKSHOP",
    "HUT",
    "LOAD",
    "HELMET",
    "WAIST",
    "BUSH",
    "BUD",
    "PRAISE",
    "FATE",
    "FENCE",
    "FRIDAY",
    "THURSDAY",
    "WEDNESDAY",
    "TUESDAY",
    "MONDAY",
    "SUNDAY",
    "SATURDAY",
    "RIVER MOUTH",
    "OATH",
    "SIGN",
    "THRESHOLD",
    "CHEEK",
    "MORTAR BINDER",
    "SKY",
    "RAINBOW",
    "OKRA",
    "PINE",
    "SPLEEN",
    "HIP",
    "BLADDER",
    "CUSTOM",
    "RIDGE",
    "BIRTHMARK",
    "TOP",
    "BRACELET",
    "WIDOW",
    "OLDER SISTER",
    "OLDER BROTHER",
    "YOUNGER BROTHER",
    "YOUNGER SISTER",
    "STONE (OF FRUIT)",
    "CLUB",
    "FOAM",
    "AXLE",
    "CARCASS",
    "ELK",
    "GRAVE",
    "TABLE",
    "SHAME",
    "BILE",
    "THUMB",
    "GUEST",
    "PAIN",
    "LOOM",
    "TELEVISION",
    "AGE",
    "LICENSE PLATE",
    "BUTTERFLY",
    "PERJURY",
    "BAT",
    "FURROW",
    "BANANA TREE",
    "HEDGEHOG",
    "GUNPOWDER",
    "HYENA",
    "DANDELION",
    "CHILD (DESCENDANT)",
    "SCREW",
    "WOOD",
    "BOMB",
    "INJECTION",
    "AFTERNOON",
    "PUS",
    "PIMPLE",
    "DANGER",
    "SOUND OR NOISE",
    "WEST",
    "BEAR",
    "BRUSH",
    "ADORNMENT",
    "COPPER",
    "CRANE",
    "SIBLING-IN-LAW",
    "DINNER (SUPPER)",
    "MARROW",
    "VAGINA",
    "VULVA",
    "NAVEL",
    "BOAT",
    "BALL",
    "QUARREL",
    "COTTON",
    "POCKET",
    "DOVE",
    "SPARROW",
    "BIRCH",
    "CROCODILE",
    "FISHERMAN",
    "BEAD",
    "DONKEY",
    "HUNGER",
    "BUZZARD",
    "COIN",
    "ANCHOR",
    "CAMEL",
    "DUIKER",
    "ANTHILL",
    "SAUSAGE",
    "REINDEER",
    "EAST",
    "COCK",
    "ARMADILLO",
    "ARMPIT",
    "PAIR",
    "ARSON",
    "PUMA",
    "QUAIL",
    "CLOTHES",
    "FINGERNAIL OR TOENAIL",
    "SPECTACLES",
    "SHOVEL",
    "SWELLING",
    "EAGLE",
    "MOLE",
    "STINGRAY",
    "RESPECT (NOUN)",
    "DEBT",
    "FIR",
    "GILL",
    "MANE",
    "TORCH",
    "VEIN",
    "ARTERY",
    "OINTMENT",
    "BAMBOO",
    "RAVINE",
    "BEESWAX",
    "BEGGAR",
    "ANUS",
    "DEER",
    "FORTRESS",
    "GUARD",
    "SOLDIER",
    "CROWN (OF HEAD)",
    "GOD",
    "IDOL",
    "INITIATION CEREMONY",
    "BASTARD",
    "SAW",
    "BEDBUG",
    "BEECH",
    "ABUSE",
    "SUNFLOWER",
    "GOITER",
    "CORNFLOWER",
    "NECKLACE",
    "LOINCLOTH",
    "BUNCH",
    "CALENDAR",
    "SOYA SAUCE",
    "MANTOU",
    "CANOE",
    "FAN (OBJECT)",
    "YOUNG GOAT (KID)",
    "DEMON",
    "CENTIPEDE",
    "DEW",
    "CHISEL",
    "WANTON",
    "WIDOWER",
    "WHIRLPOOL",
    "MOTHER'S BROTHER",
    "PATERNAL UNCLE (FATHER'S BROTHER)",
    "DISEASE",
    "CHOPSTICKS",
    "RIBES",
    "CALF",
    "INTESTINES",
    "COLLARBONE",
    "DEFECT",
    "CLOVE",
    "DITCH",
    "MASK",
    "BOLT (OF LIGHTNING)",
    "DOG",
    "COFFIN",
    "COLLAR",
    "BAIT",
    "JEALOUSY",
    "HAMMOCK",
    "PLAINTIFF",
    "CROWD",
    "PLOT",
    "PEA",
    "RICE PLANT",
    "SOYA",
    "SOYA BEAN",
    "FROST",
    "POND",
    "JANUARY",
    "FEBRUARY",
    "DRAGON",
    "MAGPIE",
    "BUCKWHEAT",
    "HEMP",
    "WALNUT",
    "PEACH",
    "PERSIMMON",
    "COLUMN",
    "APRON",
    "STRAW SANDAL",
    "CONGEE",
    "ALCOHOL (DRINK)",
    "DUSTPAN",
    "BUCKET",
    "SMALL BOWL",
    "CHOPSTICK",
    "CLAY POT",
    "WOK",
    "DUNG (ANIMAL FAECES)",
    "STOOL",
    "FOLK SONG",
    "STORY",
    "BUDDHA",
    "INTEREST",
    "CUNNING PERSON",
    "FAT (FOR NOURISHMENT)",
    "ANIMAL OR MEAT",
    "FOOT OR LEG",
    "CHILD",
    "THATCH OR ROOF",
    "FEMALE PERSON",
    "MALE PERSON",
    "HAIR OR FOREHEAD",
    "RAINING OR RAIN",
    "BELLY OR STOMACH",
    "MOUNTAIN OR HILL",
    "BOW STRING",
    "FINGER OR TOE",
    "ARM OR HAND",
    "MOUNTAIN FOOT",
    "MOUNTAIN RIDGE",
    "STONE OR ROCK",
    "EAR OR HEAR",
    "BARK OR SKIN",
    "CLAW OR NAIL",
    "BREAST OR MILK",
    "HEADGEAR",
    "TORCH OR LAMP",
    "SICKLE OR SCYTHE",
    "BRASS INSTRUMENT (HORN OR TRUMPET)",
    "MAGICIAN",
    "LEGENDARY CREATURE",
    "MUROID (MOUSE OR RAT)",
    "DAY OR SUN",
    "TREE OR WOOD",
    "SPRING OR WELL",
    "ROAST (DEVICE)",
    "MATTER",
    "PLOUGH (INSTRUMENT)",
    "EARTH (WET SUBSTANCE)",
    "GROUND",
    "BAMBOO HAT",
    "HEMP CLOTH",
    "PATERNAL AUNT (WIFE OF FATHER'S OLDER BROTHER)",
    "PATERNAL AUNT (WIFE OF FATHER'S YOUNGER BROTHER)",
    "MATERNAL AUNT (WIFE OF MOTHER'S BROTHER)",
    "PATERNAL UNCLE (FATHER'S OLDER BROTHER)",
    "PATERNAL UNCLE (FATHER'S YOUNGER BROTHER)",
    "PATERNAL AUNT",
    "MATERNAL AUNT",
    "MATERNAL GRANDMOTHER",
    "MATERNAL GRANDFATHER",
    "LEFT HAND",
    "RIGHT HAND",
    "DOORSILLS",
    "DRAGON BOAT FESTIVAL",
    "MID-AUTUMN FESTIVAL",
    "NEW YEAR'S EVE",
    "DUGOUT",
    "TASTE",
    "FRONT (PART)",
    "HORSETAIL",
    "BAD PERSON",
    "LOCATION OF EMOTIONS",
    "LOWER PART",
    "SNOUT",
    "LEDGE",
    "PEAK",
    "RABIES",
    "CHATTERER",
    "BODY PART",
    "AFFAIR",
    "BRAVE PERSON",
    "SHINE (EMITTED LIGHT)",
    "CORAL SNAKE",
    "WILD CAT",
    "BEETLE",
    "METAL",
    "BELL",
    "CATERPILLAR",
    "LEAF (LEAFLIKE OBJECT)",
    "BEER BANANA",
    "PATH",
    "FATHER-IN-LAW (OF WOMAN)",
    "FATHER-IN-LAW (OF MAN)",
    "MOTHER-IN-LAW (OF WOMAN)",
    "MOTHER-IN-LAW (OF MAN)",
    "FLESH",
    "DAUGHTER-IN-LAW (OF WOMAN)",
    "DAUGHTER-IN-LAW (OF MAN)",
    "SON-IN-LAW (OF WOMAN)",
    "SON-IN-LAW (OF MAN)",
    "POTION",
    "BREATH OR LIFE",
    "SAGO",
    "LEECH",
    "SHADOW",
    "LOUSE OR NIT",
    "SEA OR OCEAN",
    "SEMEN",
    "CLEARING",
    "ECLIPSE",
    "ESTUARY",
    "HORIZON",
    "METEROID (SHOOTING OR SHINING STAR)",
    "MILKY WAY",
    "PUDDLE",
    "VOLCANO",
    "GLASSES",
    "UVULA",
    "WRINKLE",
    "SUNSET",
    "SUNRISE",
    "DUSK",
    "VIRGIN",
    "STRAW",
    "WOODS",
    "BRONZE",
    "BROTHER-IN-LAW",
    "COOK (PERSON)",
    "SISTER-IN-LAW",
    "CHESTNUT",
    "LID (COVER, CAP)",
    "MUTE PERSON",
    "MAD PERSON",
    "LAME PERSON",
    "BACK (PART)",
    "LANDSCAPE",
    "STEEL",
    "PETROL",
    "LEPORID (RABBIT OR HARE)",
    "CRESTED MYNA",
    "YELLOW CROAKER",
    "CRAB",
    "SHRIMP",
    "EARTHWORM",
    "SILKWORM",
    "DRAGONFLY",
    "CICADA",
    "CRICKET",
    "GECKO",
    "CHINESE PLUM",
    "APRICOT TREE",
    "PEACH TREE",
    "LOTUS",
    "SWEET OLIVE",
    "MUGWORT",
    "BRAN",
    "CHAFF (HUSK)",
    "PEANUT",
    "RADISH",
    "ONION",
    "MANDARINE",
    "GARLIC",
    "BETEL NUT",
    "CUT NUT",
    "BREADFRUIT",
    "SAGO PALM",
    "SKIN (OF FRUIT)",
    "DREAM",
    "BROTHER-IN-LAW (OF MAN)",
    "FEATHER OR FUR OR HAIR",
    "AUNT OR MOTHER-IN-LAW",
    "COUSIN OR SISTER-IN-LAW",
    "GUAN OR TURKEY",
    "TURKEY",
    "UNCLE OR FATHER-IN-LAW",
    "LIANA",
    "COATI (COATIMUNDI)",
    "PECCARY",
    "BOY OR SON",
    "DAUGHTER OR GIRL",
    "JOURNEY",
    "CHIEF",
    "LOBSTER",
    "MANGO",
    "GRANDPARENT",
    "PICTURE",
    "ROBIN",
    "TOY",
    "SANTA CLAUS",
    "CHRISTMAS",
    "HOME",
    "BIRTHDAY",
    "CAKE",
    "SARONG",
    "OLDER BROTHER (OF MAN)",
    "OLDER BROTHER (OF WOMAN)",
    "YOUNGER BROTHER (OF MAN)",
    "YOUNGER BROTHER (OF WOMAN)",
    "OLDER SISTER (OF MAN)",
    "OLDER SISTER (OF WOMAN)",
    "YOUNGER SISTER (OF MAN)",
    "YOUNGER SISTER (OF WOMAN)",
    "CHANNEL",
    "MEMBER",
    "PROBLEM",
    "CLIMATE",
    "FUTURE",
    "LIBRARY",
    "LOGIC",
    "OFFICE",
    "REVOLUTION",
    "MARRIAGE",
    "THEORY",
    "TRAGEDY",
    "UNIVERSITY",
    "GUTS OR HEART",
    "ACAI PALM",
    "CAIMAN",
    "TUCUMA PALM",
    "PINEAPPLE",
    "CASHEW",
    "COCOA BEAN",
    "ELECTRIC EEL",
    "KINGFISHER",
    "PAPAYA",
    "SLOTH",
    "WOODPECKER",
    "WILD DOG",
    "LARGE WILD HERBIVORE",
    "PATH OR ROAD",
    "GRINDSTONE",
    "DINGO",
    "WOLF-LIKE ANIMAL",
    "MOON OR MONTH",
    "DISGUST",
    "WEIGHT",
    "GAME",
    "BAG",
    "LADY",
    "MALE GOAT",
    "FEMALE GOAT",
    "YAK",
    "MALE YAK",
    "FEMALE YAK",
    "MALE DOG",
    "FEMALE DOG",
    "MALE PIG",
    "FEMALE PIG",
    "ABACUS",
    "NOON",
    "POULTRY MEAT",
    "BAMBOO SHOOT",
    "ELEPHANT TUSK",
    "RATTAN",
    "OPIUM",
    "KAPOK TREE",
    "GINGER",
    "RICE HUSK",
    "GONG",
    "BEDROOM",
    "PANGOLIN",
    "PORCUPINE",
    "GIBBON",
    "CHICK",
    "CHICKEN CHICK",
    "SPOUSE",
    "CARABAO",
    "WATER BUFFALO",
    "HEARING (AURAL SENSE)",
    "SEEING (VISUAL SENSE)",
    "SMELLING (OLFACTORY SENSE)",
    "FEELING (HAPTIC SENSE)",
    "SCREAM (NOISE)",
    "HOWLING",
    "JOY",
    "LABOUR (EFFORT)",
    "POWER",
    "ABILITY",
    "SIZE (OF PERSON)",
    "BLESSED",
    "TORNADO",
    "WATERSIDE",
    "DEPTH",
    "ALTITUDE",
    "BREADTH",
    "LENGTH",
    "TRENCH (FOSSE)",
    "PIT (POTHOLE)",
    "LIME (MATERIAL)",
    "MIRACLE",
    "HERB",
    "RAVEN",
    "SHEPHERD",
    "HARROW (TOOL)",
    "BORDER",
    "CITY",
    "BARREL",
    "VEHICLE",
    "VIANDS (PROVISIONS)",
    "ORGANIC FAT OR OIL",
    "HARNESS (ARMOUR)",
    "MISERY",
    "PRINCE (RULER)",
    "OIL (FROM PLANTS)",
    "OIL (HYDROPHOBIC LIQUID)",
    "PIG FAT",
    "PATERNAL GRANDFATHER",
    "SEX (GENDER)",
    "PIGLET",
    "CASTRATED BOAR",
    "GELDING",
    "CAPON",
    "BAKER",
    "BUTCHER",
    "BEEF",
    "FEELING (EMOTION)",
    "BEAN OR PEA",
    "PENCIL",
    "TOOTHBRUSH",
    "HELICOPTER",
    "OCTOPUS",
    "WHEELCHAIR",
    "PRETZEL",
    "BENCH",
    "RACQUET",
    "SEAHORSE",
    "DARTS",
    "GLOBE",
    "WREATH",
    "HARMONICA",
    "RHINOCEROS",
    "IGLOO",
    "STILTS",
    "DOMINOES",
    "CACTUS",
    "ESCALATOR",
    "HARP",
    "DOOR KNOCKER",
    "STETHOSCOPE",
    "PYRAMID",
    "UNICORN",
    "FUNNEL",
    "ACCORDION",
    "NOOSE",
    "ASPARAGUS",
    "COMPASS",
    "TRIPOD",
    "SCROLL",
    "SPHINX",
    "TRELLIS (ARCHITECTURE)",
    "PALETTE (PAINTING)",
    "PROTRACTOR",
    "SKIN (HUMAN)",
    "SKIN (ANIMAL)",
    "FLESH OR MEAT",
    "SAGO THATCH",
    "BULB",
    "CAMERA",
    "CARD",
    "CARRIAGE",
    "CURTAIN",
    "ENGINE",
    "FLAG",
    "FRAME",
    "MAP",
    "NERVE",
    "ORANGE (FRUIT)",
    "PLANT STEM",
    "TRAY",
    "WHIP",
    "WIRE",
    "AREA UNDER HOUSE",
    "LARVA",
    "MYTHICAL BEING",
    "INK",
    "GRANDFATHER OR OLDER BROTHER",
    "MAN OR PERSON",
    "HUSBAND OR MALE PERSON",
    "HAIR (HEAD)",
    "COCONUT SHELL LADLE",
    "NET (FOR CATCHING)",
    "VIPER",
    "JACKFRUIT",
    "MIDNIGHT",
    "LADLE",
    "COAL",
    "CHARCOAL OR COAL",
    "PEOPLE OR PERSON",
    "TOENAIL",
    "UMBILICAL CORD",
    "SCAB",
    "WART",
    "SOLE (FOOT)",
    "TORSO",
    "SKELETON",
    "POINT (WITH FINGER)",
    "PENIS SHEATH",
    "HEADWATERS",
    "BIRD OF PARADISE",
    "ORAL CAVITY",
    "FIRE OR FIREWOOD",
    "SPEARTHROWER",
    "HAIR OR FUR",
    "MACHETE",
    "LUTE",
    "AUNT OR UNCLE",
    "EAGLE OR HAWK",
    "CAPRINE (GOAT OR SHEEP)",
    "CARP (FISH)",
    "CRUSTACEANS (PRAWNS OR SHRIMP)",
    "STEELYARD (BALANCE)",
    "FOOT (UNIT)",
    "LADDER OR STAIRS",
    "UNCLE (HUSBAND OF FATHER'S SISTER)",
    "PATERNAL AUNT (FATHER'S SISTER)",
    "MATERNAL UNCLE (MOTHER'S BROTHER)",
    "MATERNAL AUNT (MOTHER'S SISTER)",
    "MATERNAL UNCLE (HUSBAND OF ONE'S MATERNAL AUNT)",
    "SISTER-IN-LAW (OLDER BROTHER'S WIFE)",
    "BROTHER-IN-LAW (OLDER SISTER'S HUSBAND)",
    "BROTHER-IN-LAW (YOUNGER SISTER'S HUSBAND)",
    "BROTHER-IN-LAW (HUSBAND'S OLDER BROTHER)",
    "BROTHER-IN-LAW (HUSBAND'S YOUNGER BROTHER)",
    "SISTER-IN-LAW (HUSBAND'S OLDER SISTER)",
    "SISTER-IN-LAW (HUSBAND'S YOUNGER SISTER)",
    "GRANDSON (SON'S SON)",
    "GRANDCHILD (DAUGHTER'S OFFSPRING)",
    "SUNNY DAY",
    "CLOUDY DAY",
    "PLUM BLOSSOM",
    "APRICOT BLOSSOM",
    "PEACH BLOSSOM",
    "OSMANTHUS FRAGRANS",
    "SWEET OLIVE FLOWER",
    "UNHUSKED RICE",
    "GLUTINOUS RICE",
    "IDLE",
    "ANGULAR (SQUAREFORMED)",
    "CHICKEN NEST",
    "CHERRY",
    "WATERMELON",
    "MEAT DISHES",
    "LITCHI",
    "PORK",
    "JACKET",
    "SHAWL",
    "KITCHEN KNIFE",
    "FINGERTIP",
    "LITTLE FINGER",
    "FORENOON",
    "WILD GOOSE",
    "PIG TONGUE",
    "PIG LIVER",
    "CHICKEN EGG",
    "FOOT (MEASURE)",
    "SCALES (MEASURE INSTRUMENT)",
    "CRUCIAN CARP",
    "BIVALVIA (MUSSELS OR OYSTERS)",
    "THIS MONTH",
    "LAST MONTH",
    "NEXT MONTH",
    "FIELD (UPLAND)",
    "MOSQUITO NET",
    "SESAME",
    "RIVER OR WATER",
    "LANGUAGE OR WORD",
    "FEMALE PERSON OR MOTHER",
    "SAGO GRUB",
    "LEAF SPINE",
    "AMULET",
    "BIRTH (ACCOUCHEMENT)",
    "BLACK MAN",
    "BLACK WOMAN",
    "BLUEBERRY",
    "BREASTBONE",
    "BUSHFIRE",
    "CRAB CLAW",
    "CRAYFISH (FRESHWATER)",
    "CUTTLEFISH",
    "DIALECT",
    "ECHO",
    "EMU",
    "FORD (CROSSING)",
    "GRASSLAND",
    "HIP BONE",
    "KANGAROO RAT",
    "KANGAROO SKIN",
    "KNUCKLE",
    "LIE (FALSEHOOD)",
    "MOTH",
    "MUSSELS",
    "OYSTERS",
    "PENGUIN",
    "PYRE",
    "RUM",
    "SCROTUM",
    "SHOOTING STAR",
    "STARLIGHT",
    "SWAN",
    "WHITE MAN",
    "WHITE WOMAN",
    "WOMBAT",
    "TURMERIC",
    "CAULIFLOWER",
    "SIZE (OF OBJECT)",
    "MARCH",
    "APRIL",
    "MAY (MONTH)",
    "JUNE",
    "JULY",
    "AUGUST",
    "SEPTEMBER",
    "OCTOBER",
    "NOVEMBER",
    "DECEMBER",
    "GUEST OR STRANGER",
    "BENEFIT",
    "BOSS",
    "BUSINESS",
    "COLD (CHILL)",
    "CONVERSATION",
    "CUCKOO",
    "CURRENT (STREAM)",
    "ELEVATION",
    "FAIRY TALE",
    "FLAVOR",
    "FLOCK (OF ANIMALS)",
    "GATE",
    "HAPPINESS",
    "HOARFROST",
    "BUNDLE",
    "CALL (APPEAL)",
    "COUNT (QUANTITY)",
    "CRADLE",
    "DAMAGE (INJURY)",
    "GAP (DISTANCE)",
    "LAIR",
    "MEANING",
    "POUCH",
    "SLAB",
    "SLEEVE",
    "SLICE",
    "STATE (POLITICS)",
    "TUBE",
    "WARE",
    "LAUGHTER",
    "LEASH",
    "LONGING (WISH)",
    "MESSAGE",
    "MOORLAND",
    "NET",
    "NEWS",
    "PAW",
    "PERCH (FISH)",
    "PIKE (FISH)",
    "REASON",
    "RIBBON",
    "RIDDLE",
    "SIN",
    "SLEEP (STATE)",
    "STRAP",
    "SWARM (OF BIRDS)",
    "THOUGHT",
    "VIOLENCE",
    "WORKER",
    "DISTANCE",
    "WALK (MANNER)",
    "AREA",
    "ITEM",
    "GIFT",
    "COMPANIONSHIP",
    "HEAP",
    "HEIGHT",
    "CAMPFIRE",
    "AMOUNT",
    "PATTERN",
    "FRINGE",
    "SACK",
    "SKI",
    "TIP (OF OBJECT)",
    "STROKE (OF PEN)",
    "SUPPORT (OF OBJECT)",
    "TONE (MUSIC)",
    "WEALTH",
    "SPACE (AVAILABLE)",
    "EUCALYPT",
    "ECHIDNA",
    "WHITE COCKATOO",
    "WAGTAIL",
    "GRUB",
    "BANDICOOT",
    "BLACK COCKATOO",
    "BLACK DUCK",
    "PATERNAL GRANDMOTHER",
    "FIRE STICK",
    "MONITOR LIZARD",
    "NATIVE CAT",
    "SAND HILL",
    "BLUE TONGUED SKINK",
    "TOP GRINDSTONE",
    "BOTTOM GRINDSTONE",
    "BRIDE PRICE",
    "BARN OR SHED",
    "CONJUNCTIVITIS",
    "COOKED CORN",
    "GRAVEL",
    "SUGAR PALM",
    "LONTAR PALM",
    "MORINGA TREE",
    "STARFISH",
    "GREEN COCONUT",
    "RIPE COCONUT",
    "TREETOP",
    "SAME-SEX OLDER SIBLING",
    "SAME-SEX YOUNGER SIBLING",
    "DIFFERENT-SEX OLDER SIBLING",
    "DIFFERENT-SEX YOUNGER SIBLING",
    "PATERNAL AUNT (FATHER'S OLDER SISTER)",
    "MATERNAL AUNT (MOTHER'S OLDER SISTER)",
    "MATERNAL AUNT (MOTHER'S YOUNGER SISTER)",
    "BOVINE",
    "FODDER",
    "HOT SEASON",
    "MOUTH HARP",
    "COURAGE",
    "SEEDLING",
    "REED PIPE",
    "ERHU",
    "FLAIL",
    "MALARIA",
    "PHEASANT",
    "PHLEGM",
    "TURNIP",
    "RAMIE",
    "RUST",
    "SADDLE",
    "SCARF OR TURBAN",
    "CLEAVER",
    "SLOPE",
    "SWALLOW (BIRD)",
    "HIGHLAND BARLEY",
    "CROPS",
    "BALLOON",
    "BLACKBOARD",
    "CARROT",
    "COMPUTER",
    "PACIFIER",
    "ENVELOPE",
    "GIRAFFE",
    "GUITAR",
    "LEMON",
    "LIGHTER",
    "LIPSTICK",
    "PAINTBRUSH",
    "POSTMAN",
    "RACKET",
    "SEWING MACHINE",
    "SNOWMAN",
    "SOFA",
    "SUNGLASSES",
    "SWING",
    "TANK",
    "TENNIS BALL",
    "THERMOMETER",
    "UMBRELLA",
    "WARDROBE",
    "WHISTLE (INSTRUMENT)",
    "OAR",
    "STRAWBERRY",
    "LADYBUG",
    "VEST",
    "TAMBOURINE",
    "BISON",
    "POLAR BEAR",
    "GORILLA",
    "HIPPOPOTAMUS",
    "CHEETAH",
    "HAMSTER",
    "MEERKAT",
    "ARMLET",
    "BOX OR CHEST",
    "MUNTJACS",
    "LORD",
    "WILD BOAR",
    "DIBBLE STICK",
    "GEBANG PALM",
    "CIVET",
    "RICE EAR BUG",
    "BURDEN STICK",
    "CROSS-COUSIN",
    "SERMON",
    "DOWRY",
    "TREATY",
    "RINGWORM",
    "SCABIES",
    "TINEA",
    "RACK (FOR STORING FOOD)",
    "BALE-BALE (RAISED PLATFORM IN HOUSE)",
    "RITUAL GROUND",
    "CORAL ROCK",
    "MUSTARD",
    "MARRIAGE OR WEDDING",
    "BRONZE OR COPPER",
    "CROSSBOW",
    "SUSPICION",
    "COUNTRYSIDE",
    "CANNON",
    "CANNON OR GUN",
    "GRAVEN IMAGE",
    "ELF OR FAIRY",
    "CENTER OR MIDDLE",
    "KNIFE (FOR EATING)",
    "HOPE (FAITH)",
    "TIN OR TINPLATE",
    "MATERNAL UNCLE",
    "PLANTAGO",
    "TWIG",
    "BRANCH OR TWIG",
    "BOW OR CROSSBOW",
    "DEITY",
    "PELT",
    "SMALL KNIFE",
    "BAMBOO MAT",
    "CORIANDER",
    "CYPRESS",
    "EAR (OF GRAIN)",
    "FROG (SMALL)",
    "KIWIFRUIT",
    "MAPLE TREE",
    "MATERNAL UNCLE (MOTHER'S OLDER BROTHER)",
    "MATERNAL UNCLE (MOTHER'S YOUNGER BROTHER)",
    "MOLD (GET ROTTEN)",
    "PANCREAS",
    "PRICKLY ASH",
    "YOUNG ANIMAL",
    "POINT (POINTED END)",
    "BITTER BUCKWHEAT",
    "CLITORIS",
    "FALCON",
    "GORAL",
    "HORNBILL",
    "HORNET",
    "HORSEFLY",
    "LAP",
    "TRIVET",
    "FINGER MILLET",
    "FOXTAIL MILLET",
    "PULSE",
    "QUESTION",
    "PORCH",
    "SEROW",
    "FLYING SQUIRREL",
    "TAKIN",
    "CLOUD OR FOG",
    "SUNSHINE",
    "MANTIS",
    "TUSK",
    "JOB'S TEARS",
    "GROOM",
    "CAGE",
    "GRAVEYARD",
    "RICE FLOUR",
    "LARGE BOWL",
    "WEED",
    "UNCOOKED RICE",
    "PRECIPICE OR SLOPE",
    "APE OR MONKEY",
    "PICTURE (PAINTING)",
    "PICTURE (PHOTOGRAPH)",
    "SHORE OR BANK",
    "FLOWING BODY OF WATER",
    "JACKAL",
    "LYNX",
    "FLAX",
    "HOPS",
    "ELM",
    "OAR OR PADDLE",
    "JEW’S HARP",
    "SNARE (TRAP)",
    "POND OR LAKE",
    "SNOW OR ICE",
    "MONSOON SEASON",
    "IRON OR METAL",
    "PEARL",
    "LEATHER OR HIDE",
    "YEARLING (HORSE)",
    "LENTILS",
    "PRIEST OR SHAMAN",
    "RITE",
    "SACRED GROVE",
    "BURIAL MOUND",
    "POLAR STAR",
    "MORNING STAR",
    "EVENING STAR",
    "URSA MAJOR",
    "ORION’S BELT",
    "SIDE (BODY)",
    "WRISTWATCH",
    "THIRD DAY OF THE MONTH",
    "SIEVE (TOOL)",
    "FIRST DAY OF THE MONTH",
    "SECOND DAY OF THE MONTH",
    "INCENSE",
    "CUPBOARD",
    "SPROUT (SHOOT)",
    "BAMBOO BASKET",
    "OFFICIAL",
    "BOILED WATER",
    "PIMPLEFACE",
    "STUTTERER",
    "POWDER",
    "PIGSTY",
    "GALL BLADDER",
    "HAN CHINESE",
    "TIBETAN",
    "PATIENT (SICK PERSON)",
    "ROBBER",
    "EMPEROR",
    "HORSE DUNG",
    "PIG DUNG",
    "HUNTING DOG",
    "SHEEP DUNG",
    "PEACOCK",
    "WEASEL",
    "ALUMINIUM",
    "SULPHUR",
    "MIDDLE FINGER",
    "PLACENTA",
    "MEASLES",
    "WILD RICE",
    "RICE STRAW",
    "MUER (FUNGUS)",
    "LEAN MEAT",
    "SHEEP MEAT",
    "SICHUAN PEPPER",
    "BUILDING",
    "ROUNDWORM",
    "GOURD OR MELON",
    "WAREHOUSE",
    "COWSHED",
    "HENHOUSE",
    "SHEEPFOLD",
    "HORSE BARN",
    "TILE",
    "RULER",
    "MERCHANDISE",
    "FILE (TOOL)",
    "PLANE (TOOL)",
    "EARTHEN JUG",
    "WASP NEST",
    "BALDHEAD",
    "DRILL",
    "SHEATH",
    "JOKE",
    "SURNAME",
    "DIRECTION",
    "RICE STEAMER",
    "SHOULDER POLE",
    "AUTONYM (OF PEOPLE)",
    "COW DUNG",
    "FAT MEAT",
    "WHITE (OF EGGS)",
    "BROWN SUGAR",
    "WHITE SUGAR",
    "COTTON WOOL",
    "TOFU",
    "WAX GOURD",
    "YARN",
    "KISS (NOUN)",
    "HEADBAND OR HEADDRESS",
    "SILENCE",
    "BEACH",
    "FLAX OR LINEN",
    "RIVERBANK",
    "SHORE OF LAKE",
    "SHORE OF SEA",
    "HELP (ASSISTANCE)",
    "KINDNESS",
    "LEVEL",
    "LIAR",
    "OBLIGATION (DUTY)",
    "DANCE (MOVEMENT)",
    "STRAW RAINCOAT",
    "HARVEST OR HARVEST SEASON",
    "PREPARED FOOD",
    "HORSE MANE",
    "BIRD NEST",
    "HELLO",
    "GOODBYE",
    "EARTH OR LAND",
    "STURGEON",
    "MOCCASIN",
    "WARRIOR",
    "TOWN OR VILLAGE",
    "MALLARD",
    "AMERICAN BLACK BEAR",
    "INDIGENOUS PEOPLES OF THE AMERICAS",
    "LOWER BACK",
    "DISABLED PERSON",
    "BURN (INJURY)",
    "INTESTINAL WORM",
    "LEPROSY",
    "HEADACHE",
    "PLAN",
    "ADULT",
    "CO-WIFE",
    "WEAVER",
    "AGREEMENT",
    "PROVERB",
    "MUSH (FOOD)",
    "COOKING POT",
    "GRANARY",
    "BELLOWS",
    "RICH PERSON",
    "POOR PERSON",
    "COWRIE SHELL",
    "MOURNING",
    "ANTELOPE",
    "ZEBRA",
    "SHREW",
    "MONGOOSE",
    "ELEPHANT TRUNK",
    "PARTRIDGE",
    "CORN HUSK",
    "DESERT",
    "MARSH",
    "BUBBLE",
    "FULL MOON",
    "NEW MOON",
    "HOT WEATHER",
    "COLD WEATHER",
    "MOVEMENT",
    "ODOR (SMELL)",
    "TIE (NOUN)",
    "RAINCOAT",
    "PHARYNX",
    "LARYNX",
    "BELLYBUTTON",
    "OVARY",
    "BADGER",
    "GUINEA PIG",
    "MARMOT",
    "BUDGERIGAR",
    "FINCH",
    "FLAMINGO",
    "NIGHTINGALE",
    "STORK",
    "AVOCADO",
    "BROCCOLI",
    "CELERY",
    "COURGETTE",
    "LETTUCE",
    "APRICOT",
    "LYCHEE",
    "POMEGRANATE",
    "FERRY",
    "CHIMPANZEE",
    "INSTEP",
    "GRIZZLY BEAR",
    "MARTEN",
    "WHIRLWIND",
    "BATTLE CRY (WAR WHOOP)",
    "POCKETKNIFE",
    "BRASS",
    "INTERPRETER",
    "CRANE (DEVICE)",
    "VASE",
    "SHAPE",
    "DROP (OF A LIQUID)",
    "HATE (LOATHING)",
    "PATERNAL UNCLE",
    "STORING POT",
    "WATER POT",
    "RICE SEEDLING",
    "GRAPEVINE",
    "CATFISH",
    "DAUGHTER (OF MALE EGO)",
    "SON (OF MALE EGO)",
    "PET",
    "SISTER-IN-LAW (OF FEMALE EGO)",
    "GRANDCHILD (OF FEMALE EGO)",
    "ALBATROSS",
    "OSTRICH",
    "STINGER",
    "FISHBONE",
    "IVORY",
    "DATE (FRUIT)",
    "FERN",
    "RASPBERRY",
    "GRAPEFRUIT OR POMELO",
    "EYEBALL",
    "JUNGLE",
    "BOULDER",
    "MIRITI PALM",
    "ALMOND",
    "WAXING MOON",
    "WANING MOON",
    "CALM (OF SEA)",
    "BROOK",
    "MALE COUSIN",
    "FEMALE COUSIN",
    "HINNY",
    "MALE CAT",
    "ROE DEER",
    "HEALTHINESS",
    "DINNER (MAIN MEAL)",
    "WALL",
    "LOVE (AFFECTION)",
    "HANDSPAN",
    "BROAD BEAN",
    "CRANBERRY",
    "WINDMILL",
    "ONE THIRD",
    "CONTEMPT",
    "DISAPPOINTMENT",
    "EXCITEMENT",
    "INTEREST (FEELING)",
    "SURPRISE (FEELING)",
    "TRIUMPH",
    "AMUSEMENT",
    "AWE",
    "CONCENTRATION",
    "CONFUSION",
    "SADNESS",
    "EGGSHELL",
    "MIDWIFE",
    "POSSESSIONS",
    "ABORTION",
    "ALCOHOLIC (PERSON)",
    "ALLERGY",
    "MURDERER",
    "CHOCOLATE",
    "KNOWLEDGE",
    "CRIMINAL",
    "DENTIST",
    "DEPRESSION",
    "DIAMOND",
    "FIGHT (COMBAT)",
    "PISTOL",
    "ROSE",
    "TARANTULA",
    "SKUNK",
    "NEPHEW OR NIECE",
    "EARHOLE",
    "NATURE",
    "FATHER (OF A WOMAN)",
    "FATHER (OF A MAN)",
    "MOTHER (OF A WOMAN)",
    "MOTHER (OF A MAN)",
    "GRANDCHILD (SON'S OFFSPRING)",
    "STEPCHILD",
    "COW MILK",
    "BREAST MILK",
    "COUGH (ACT OF COUGHING)",
    "PRIDE",
    "PLEASURE",
    "DEVIL",
    "CALABASH",
    "PEACH PALM",
    "GENIPA",
    "TINAMOU",
    "PACU",
    "FEMALE ANIMAL",
    "MALE ANIMAL",
    "BABAÇU (Attalea speciosa)",
    "BABY CARRIER",
    "BLUE-AND-YELLOW MACAW (Ara ararauna)",
    "BRAZIL NUT (Bertholletia excelsa)",
    "BRAZILIAN CEDAR (Cedrela odorata)",
    "DAUGHTER OF WOMAN",
    "EMBAUBA (genus Cecropia)",
    "GRIDIRON",
    "HOPLIAS (genus)",
    "INGA (genus)",
    "LARGE-BULLET-ANT (subfamily Paraponerinae)",
    "MOUNTAIN SOURSOP (Annona montana)",
    "PIUM (simuliidae)",
    "RED-AND-GREEN MACAW (Ara chloropterus)",
    "SON OF WOMAN",
    "TAPIOCA",
    "TAYRA (Eira barbara)",
    "WAX",
    "WRISTBAND",
    "LOWER LIP",
    "ORION'S CONSTELLATION",
    "BABY SLING",
    "HONEYCOMB",
    "SHOTGUN",
    "RED-FOOTED TORTOISE",
    "LIBER (INNER BARK)",
    "PANDA",
    "REFRIGERATOR",
    "CHARITY",
    "FRIENDSHIP",
    "HOSTILITY",
    "DISPUTE",
    "SYSTEM",
    "SOCIETY",
    "RELATIONSHIP",
    "IDENTITY",
    "TEAM",
    "DISCIPLINE",
    "SCENERY",
    "SPLENDOR",
    "TRAUMA",
    "CONCEPT",
    "CONTENT",
    "EFFECT",
    "RESULT",
    "PROCESS",
    "METHOD"
  ];
  
  let property = [
    "CONTEMPTIBLE",
    "BRAVE",
    "UNPLEASANT",
    "KEEN",
    "STINKING",
    "EVIL",
    "LIQUID",
    "SOBER",
    "BRACKISH",
    "SQUINT-EYED",
    "INNOCENT",
    "INSOLENT",
    "GRADUALLY",
    "FAITHFUL",
    "SATIATED",
    "FOREIGN",
    "HUMID",
    "SORROWFUL",
    "ITCHY",
    "GREY",
    "RED",
    "BLACK",
    "PROUD",
    "RIPE",
    "SHALLOW",
    "SPARSE",
    "RARE",
    "INTACT",
    "LAVISH",
    "FRESH",
    "LEFT",
    "LIGHT (COLOR)",
    "CALM",
    "ROUGH (OF SEA)",
    "COOKED",
    "CROOKED",
    "LAME",
    "POINTED",
    "FRAGRANT",
    "LOUD",
    "BLUNT",
    "WRINKLED",
    "SEVERE",
    "BE LATE",
    "SHY",
    "CRUEL",
    "CERTAIN",
    "STRONG EFFECT",
    "DREADFUL",
    "INFLATED",
    "SCANTY",
    "SPICY",
    "INFECTED",
    "YOUNG (OF WOMAN)",
    "YOUNG (OF MAN)",
    "OLD (OF MAN)",
    "OLD (OF WOMAN)",
    "KIND OR POLITE",
    "DIFFICULT",
    "BROKEN",
    "CLOSED",
    "NAKED",
    "STRANGE",
    "EARLY",
    "BRIGHT",
    "EASY",
    "WISE",
    "SAD",
    "SLOW",
    "CLEAN",
    "DARK",
    "TALL",
    "RICH",
    "SWEET",
    "LOW",
    "STRONG",
    "READY",
    "SKILLED",
    "AWAKE",
    "BLUE",
    "THIRSTY",
    "OPPOSITE",
    "BITTER",
    "POISONOUS",
    "BORING",
    "GREASY",
    "CLEAR",
    "DEAF",
    "RIGHT",
    "GOOD",
    "LIGHT (WEIGHT)",
    "VULGAR",
    "SALTY",
    "HONEST",
    "SECRET",
    "PREGNANT",
    "BALD",
    "PAINFUL",
    "PURE",
    "BIG",
    "LONG",
    "YOUNG",
    "HEAVY",
    "OLD",
    "DIRTY",
    "NEW",
    "WARM",
    "SMOOTH",
    "WIDE",
    "THICK",
    "SMALL",
    "HIGH",
    "NARROW",
    "FAT (OBESE)",
    "IMPORTANT",
    "HOT",
    "COLD",
    "BAD",
    "CLEVER",
    "QUIET",
    "WHITE",
    "HEALTHY",
    "WRONG",
    "ROUND",
    "SHARP",
    "DULL",
    "DRY",
    "THIN (SLIM)",
    "STRAIGHT",
    "FAR",
    "RUDE",
    "YELLOW",
    "GREEN",
    "EXPENSIVE",
    "BEAUTIFUL",
    "FULL",
    "DRUNK",
    "EXACT",
    "DUMB",
    "HAPPY",
    "STUPID",
    "UGLY",
    "FEMALE",
    "GLOOMY",
    "MALE",
    "SIMILAR",
    "LAZY",
    "EQUAL",
    "SURPRISED",
    "DEEP",
    "WEAK",
    "EMPTY",
    "DEAD",
    "FAST",
    "FLAT",
    "MOTIONLESS",
    "SHORT",
    "BLIND",
    "TRUE",
    "MUTE",
    "POOR",
    "GUILTY",
    "FLEXIBLE",
    "CURVED",
    "HOLY",
    "CORRECT (RIGHT)",
    "WET",
    "ROTTEN",
    "TIRED",
    "OBSCURE",
    "TASTELESS",
    "STINGY",
    "TASTY",
    "DEXTEROUS",
    "ANGRY",
    "OBSTINATE",
    "SICK",
    "SOFT",
    "ACTIVE",
    "AMAZING",
    "VISIBLE",
    "PASSIONATE",
    "HARD",
    "CHEAP",
    "ASHAMED",
    "MAD",
    "ASTONISHED",
    "SOUR",
    "ATTENTIVE",
    "ROUGH",
    "NEAR",
    "GENTLE",
    "UNRIPE",
    "RAW",
    "ALONE",
    "MERRY",
    "GREEDY",
    "DILIGENT",
    "PAINFUL OR SICK",
    "WARM (OF WEATHER)",
    "OLD (AGED)",
    "OLD (USED)",
    "COARSE",
    "FINE OR THIN",
    "LIGHT (IN TASTE)",
    "LOW (HEIGHT)",
    "FRESH (OF WATER)",
    "LIGHT (SMELL OR TASTE)",
    "HIGH-RANKING",
    "RABID",
    "EXPERIENCED",
    "LEAN (MEAT)",
    "GLARING",
    "UNTAMED OR WILD",
    "KEEN OR SUBTLE",
    "LOVELY",
    "DENSE",
    "THIN (OF SHAPE OF OBJECT)",
    "FEMALE (OF PERSON)",
    "MALE (OF PERSON)",
    "FEMALE (OF ANIMAL)",
    "MALE (OF ANIMAL)",
    "HOT OR WARM",
    "IDENTICAL",
    "WHOLE",
    "GREEN OR UNRIPE",
    "CIRCULAR (ROUND IN TWO DIMENSIONS)",
    "SPHERICAL (ROUND IN THREE DIMENSIONS)",
    "THIN (OF HAIR AND THREAD)",
    "THIN (OF LEAF AND CLOTH)",
    "THIN (OF HAIR AND LEAF)",
    "THIN",
    "FREE",
    "CUNNING",
    "SUNNY",
    "CLOUDY",
    "VERTICAL",
    "HORIZONTAL",
    "BLUE OR GREEN",
    "BROWN",
    "GOOD-LOOKING",
    "FAT (OF MEAT AND FOOD)",
    "PURPLE",
    "AGAINST",
    "DEAR",
    "COLD (OF WEATHER)",
    "SMALL (NOT TALL)",
    "ADORNED",
    "DIFFERENT",
    "LOOSE",
    "DISGUSTING",
    "CROWDED",
    "SMART",
    "BROAD",
    "BLACK OR DARK",
    "BROAD OR WIDE",
    "STEEP",
    "STRONG (OF DRINK)",
    "FAT (OILY)",
    "BUSY",
    "CAREFUL",
    "HIGH OR TALL",
    "JEALOUS",
    "LEFT HANDED",
    "TAME",
    "COLORFUL",
    "DAMP",
    "LIVING",
    "POWERFUL",
    "PRECIOUS",
    "SOLID",
    "FAMILIAR",
    "SCARED",
    "COPPER (COLOR)",
    "TIGHT",
    "FALSE",
    "SLANTED",
    "DROWNED",
    "MIGHTY OR POWERFUL OR STRONG",
    "BROKEN (NOT WORKING)",
    "BROKEN (SHATTERED)",
    "BE LEFT",
    "OPEN (STATE)",
    "KIND",
    "POLITE",
    "ORANGE (COLOR)",
    "TALL (PERSON)",
    "QUICKLY",
    "PINK",
    "DANGEROUS",
    "WATERY",
    "LIGHT BLUE",
    "LIGHT GREEN",
    "SLEEPY",
    "GENEROUS",
    "CURIOUS",
    "STUBBORN",
    "LOST",
    "HOLLOW",
    "SLIPPERY",
    "STICKY",
    "DARK YELLOW",
    "BEIGE",
    "FEELING SORE",
    "BRILLIANT",
    "CLEAR (TO SEE)",
    "NEAR (IN SPACE)",
    "BAREFOOT",
    "KHAKI",
    "BRIGHT YELLOW",
    "LILAC",
    "MAGENTA",
    "TRANSPARENT",
    "MOUNTAINOUS",
    "FLORAL",
    "MUGGY",
    "WINDY",
    "FOGGY",
    "THUNDERY",
    "EMOTIONAL",
    "SAFE",
    "BAD OR EVIL",
    "DARK GREEN",
    "SHY OR ASHAMED",
    "RIPE OR COOKED",
    "COWARDLY",
    "DISOBEDIENT",
    "HANDSOME",
    "HOT (FEELING HOT)",
    "COLD (FEELING COLD)",
    "PREGNANT (OF ANIMALS)",
    "BE CALLED BY NAME",
    "HALF (HALF OF)",
    "ASTRINGENT",
    "CONFUSED",
    "ANXIOUS",
    "RUSTY",
    "BLOND",
    "NOISY",
    "PATIENT",
    "IMPATIENT",
    "CLUMSY",
    "TURQUOISE",
    "EXCITED",
    "DEPRESSED",
    "UNHAPPY",
    "NERVOUS"
  ];
  
  let topic = [
    "lotus",
    "saint",
    "galaxy",
    "ballerina",
    "thumbelina",
    "fairy dance",
    "hummingbird",
    "dream theory",
    "wondrous night",
    "dance by design",
    "dance of spring",
    "goddess of music",
    "dancing in heaven",
    "spiritual beings in the universe",
    "women who want to be free inside and out"
  ];
  
  let adjective = ["cool", "angelic"];
  
  let medium = [
    "print",
    "poster",
    "drawing",
    "painting",
    "watercolor",
    "digital art",
    "concept art",
    "illustration",
    "colored pencil"
  ];
  
  let likelyWhiteFirstName = [
    "Kimberly",
    "Kim",
    "Shannon",
    "Lindsay",
    "Brooke",
    "Jennifer",
    "Stephanie",
    "Sarah",
    "Amy",
    "Jessica",
    "Heather",
    "Melissa",
    "Lissa",
    "Amanda",
    "Manda",
    "Nicole",
    "Niki",
    "Angela",
    "Angie",
    "Lisa",
    "Kelly",
    "Elizabeth",
    "Liz",
    "Rebecca",
    "Becca",
    "Christina",
    "Christa",
    "Crystal"
  ];
  
  let distinctivelyBlackFirstName = [
    "Cassietta",
    "Cleotha",
    "Deiondre",
    "Dericia",
    "Gaynelle",
    "Kacondra",
    "Kanesha",
    "Keilantra",
    "Kendis",
    "Keshon",
    "Lachelle",
    "Lakin",
    "Lanelle",
    "Laquanna",
    "Laqueta",
    "Laquinta",
    "Lashawn",
    "Latanya",
    "Latonya",
    "Latoya",
    "Mekell",
    "Moesha",
    "Muncel",
    "Najwa",
    "Nakeisha",
    "Nichelle",
    "Niesha",
    "Quanella",
    "Quanesha",
    "Quisha",
    "Ranielle",
    "Ronnell",
    "Shandra",
    "Shaquana",
    "Shateque",
    "Sidone",
    "Talaitha",
    "Talisa",
    "Talisha",
    "Tamika",
    "Tamira",
    "Tamyra",
    "Tanasha",
    "Tandice",
    "Tanginika",
    "Taniel",
    "Tanisha",
    "Tariana",
    "Temima"
  ];
  
  let lName = [
    "Gray",
    "Scott",
    "James",
    "Watson",
    // Banned! "Cox",
    "Thompson",
    "Clark",
    "Miller",
    "Allen",
    "Evans",
    "Price",
    "Richardson",
    "Lewis",
    "Wilson",
    "Brooks",
    "Powell",
    "Foster",
    "Fisher",
    "Sanchez",
    "Carter"
  ];
  
  let stats = [
    "Feelings",
    "Strength",
    "Charisma",
    "Willpower",
    "Wisdom",
    "Intelligence",
    "Dexterity",
    "Agility",
    "Cool",
    "Hot",
    "Sharp",
    "Weird",
    "Stamina",
    "Constitution",
    "Manipulation",
    "Comeliness",
    "Edge",
    "Power",
    "Feel",
    "Ninja",
    "Warrior",
    "Essence",
    "Cyber",
    "Hack",
    "Synth",
    "Cool",
    "Meat",
    "Mind",
    "Style",
    "Cold",
    "Volatile",
    "Dark",
    "Light",
    "Red",
    "Green",
    "Blue",
    "Black",
    "White",
    "Purple",
    "Empathy",
    "Sympathy",
    "Awareness",
    "Appearance",
    "Wit",
    "Wits",
    "Cheese",
    "Flavor",
    "Soldier",
    "Medic",
    "Scout",
    "Cleric"
  ];
  
  let good_status = [
    "_____",
    "awake",
    "invisible",
    "alert",
    "alive",
    "in control",
    "benefitting",
    "good",
    "magic",
    "friendly",
    "free",
    "allied",
    "fresh",
    "unwounded",
    "healthy",
    "active",
    "charged",
    "sharp",
    "quick",
    "hidden",
    "quiet",
    "happy",
    "joyful",
    "ecstatic",
    "observant",
    "knowledgable",
    "witty"
  ];
  
  let bad_status = [
    "_____",
    "tired",
    "evil",
    "misleading",
    "sleepy",
    "hungry",
    "angry",
    "depressed",
    "hostile",
    "anxious",
    "furious",
    "jammed",
    "hacked",
    "overloaded",
    "distressed",
    "distraught",
    "flummoxed",
    "lost",
    "alone",
    "broken",
    "missing",
    "fired",
    "unemployed",
    "nasty",
    "shunned",
    "expensive",
    "wasteful",
    "noisy",
    "damaged",
    // "allied with the #enemy#",  "// TODO(johnicholas): fix this
    "empty",
    "heavy",
    "slow",
    "nervous",
    "anxious",
    "sad",
    "dying",
    "bleeding",
    "burning",
    "obvious"
  ];
  
  let search = [
    "investigate",
    "interrogate",
    "examine",
    "pore over",
    "research",
    "look into the history of",
    "spend time studying",
    "study"
  ];
  
  let article = [
    "the",
    "a",
    "their",
    "your",
    "another"
    // "#status.a#",  "// TODO(johnicholas)
    // "the #status#"  "// TODO(johnicholas)
  ];
  
  let location = [
    "room",
    "area",
    "location",
    "scene",
    "building",
    "fortress",
    "HQ",
    "road",
    "highway",
    "town",
    "village",
    "city",
    "state",
    "nation"
  ];
  
  let friend = [
    "_____",
    "team member",
    "team",
    "friend",
    "ally",
    "partner",
    "guardian",
    "boss",
    "commander",
    "leader"
  ];
  
  let enemy = [
    "_____",
    "enemy",
    "monster",
    "target",
    "goal",
    "nemesis",
    "adversary"
  ];
  
  let vs_verb = ["harm", "fight", "defeat", "disarm", "challenge"];
  
  let coop_verb = ["help", "heal", "assist", "enchant", "bolster"];
  
  let weapon = [
    "sword",
    "ranged weapon",
    "melee weapon",
    "bullet",
    "missile",
    "weapon",
    "gun",
    "knife",
    "club",
    "sharp object",
    "brick",
    "axe",
    "bow",
    "rifle",
    "shotgun",
    "cyberdeck",
    "dart gun",
    "crossbow",
    "grenade",
    "bomb",
    "fist",
    "blade",
    "needle"
  ];
  
  let tool = [
    "lantern",
    "lockpick",
    "quiver",
    "clip",
    "use of ammunition",
    "charge",
    "battery",
    "spellbook",
    "phone",
    "device",
    "tool"
  ];
  
  let degree = [
    "light",
    "medium",
    "serious",
    "critical",
    "recoverable",
    "unrecoverable",
    "2",
    "3",
    "10",
    "infinite",
    "nominal"
  ];
  
  let damage = [
    "damage",
    "wounds",
    "grief",
    "stun",
    "distress",
    "trauma",
    "disbelief",
    "horror",
    "chaos",
    "burn",
    "freeze",
    "shock",
    "rot",
    "sear",
    "purity"
  ];
  
  let mod_phrase = ["forward the next time you", "ongoing whenever you"];
  
  let here = ["here", "there"];
  
  module.exports = {
    action_process,
    person_thing,
    property,
    topic,
    adjective,
    medium,
    likelyWhiteFirstName,
    distinctivelyBlackFirstName,
    lName,
    stats,
    good_status,
    bad_status,
    search,
    article,
    location,
    friend,
    enemy,
    vs_verb,
    coop_verb,
    weapon,
    tool,
    degree,
    damage,
    mod_phrase,
    here,
    labels,
    letters
  };
  